// cardio_data.js — Real mesh name → data mapping for human-cardiovascular-system.glb
// Model source: Human Atlas / BodyParts3D (CC BY-SA 2.1 Japan)

export const CARDIO_CATEGORIES = [
  { id: 'heart',    label: 'ccat_heart' },
  { id: 'arteries', label: 'ccat_arteries' },
  { id: 'veins',    label: 'ccat_veins' },
];

// meshKeywords: strings found in lowercased mesh name map to this entry
export const CARDIO_DB = [
  // ─── Heart ──────────────────────────────────────────────────────────────────
  {
    id: 'cardio_heart',
    name: 'c_heart',
    latinName: 'Cor',
    category: 'heart',
    meshKeywords: ['valvular complex of heart', 'arteries of heart', 'heart.j'],
    description: 'cdesc_heart',
    function: 'cfunc_heart',
    clinicalNotes: 'cclin_heart',
    relatedStructures: ['cardio_aorta', 'cardio_vena_cava', 'cardio_pulmonary_artery'],
  },
  {
    id: 'cardio_right_ventricle',
    name: 'c_right_ventricle',
    latinName: 'Ventriculus dexter',
    category: 'heart',
    meshKeywords: ['right ventricle.001', 'right ventricle'],
    description: 'cdesc_right_ventricle',
    function: 'cfunc_right_ventricle',
    clinicalNotes: 'cclin_right_ventricle',
    relatedStructures: ['cardio_heart', 'cardio_pulmonary_artery'],
  },
  {
    id: 'cardio_left_ventricle',
    name: 'c_left_ventricle',
    latinName: 'Ventriculus sinister',
    category: 'heart',
    meshKeywords: ['left ventricle.001', 'left ventricle'],
    description: 'cdesc_left_ventricle',
    function: 'cfunc_left_ventricle',
    clinicalNotes: 'cclin_left_ventricle',
    relatedStructures: ['cardio_heart', 'cardio_aorta'],
  },
  {
    id: 'cardio_right_atrium',
    name: 'c_right_atrium',
    latinName: 'Atrium dextrum',
    category: 'heart',
    meshKeywords: ['right atrium.001', 'right atrium'],
    description: 'cdesc_right_atrium',
    function: 'cfunc_right_atrium',
    clinicalNotes: 'cclin_right_atrium',
    relatedStructures: ['cardio_heart', 'cardio_vena_cava'],
  },
  {
    id: 'cardio_left_atrium',
    name: 'c_left_atrium',
    latinName: 'Atrium sinistrum',
    category: 'heart',
    meshKeywords: ['left atrium.001', 'left atrium'],
    description: 'cdesc_left_atrium',
    function: 'cfunc_left_atrium',
    clinicalNotes: 'cclin_left_atrium',
    relatedStructures: ['cardio_heart', 'cardio_pulmonary_vein'],
  },

  // ─── Aorta & Major Arteries ───────────────────────────────────────────────
  {
    id: 'cardio_aorta',
    name: 'c_aorta',
    latinName: 'Aorta',
    category: 'arteries',
    meshKeywords: ['root of aorta', 'thoracic aorta', 'aortic bifurcation', 'aorta.j'],
    description: 'cdesc_aorta',
    function: 'cfunc_aorta',
    clinicalNotes: 'cclin_aorta',
    relatedStructures: ['cardio_heart', 'cardio_carotid_artery'],
  },
  {
    id: 'cardio_systemic_arteries',
    name: 'c_systemic_arteries',
    latinName: 'Arteriae systemicae',
    category: 'arteries',
    meshKeywords: ['systemic arteries.j'],
    description: 'cdesc_systemic_arteries',
    function: 'cfunc_systemic_arteries',
    clinicalNotes: 'cclin_systemic_arteries',
    relatedStructures: ['cardio_aorta'],
  },
  {
    id: 'cardio_cerebral_arteries',
    name: 'c_cerebral_arteries',
    latinName: 'Arteriae cerebrales',
    category: 'arteries',
    meshKeywords: ['cerebral arterial circle', 'arteries of spinal cord'],
    description: 'cdesc_cerebral_arteries',
    function: 'cfunc_cerebral_arteries',
    clinicalNotes: 'cclin_cerebral_arteries',
    relatedStructures: ['cardio_aorta', 'cardio_carotid_artery'],
  },
  {
    id: 'cardio_carotid_artery',
    name: 'c_carotid_artery',
    latinName: 'Arteria carotis communis',
    category: 'arteries',
    meshKeywords: ['carotid artery', 'carotid.001'],
    description: 'cdesc_carotid',
    function: 'cfunc_carotid',
    clinicalNotes: 'cclin_carotid',
    relatedStructures: ['cardio_aorta'],
  },
  {
    id: 'cardio_pulmonary_artery',
    name: 'c_pulmonary_artery',
    latinName: 'Arteria pulmonalis',
    category: 'arteries',
    meshKeywords: ['pulmonary artery', 'lobar artery', 'segmental artery'],
    description: 'cdesc_pulmonary_artery',
    function: 'cfunc_pulmonary_artery',
    clinicalNotes: 'cclin_pulmonary_artery',
    relatedStructures: ['cardio_right_ventricle'],
  },

  // ─── Veins ────────────────────────────────────────────────────────────────
  {
    id: 'cardio_vena_cava',
    name: 'c_vena_cava',
    latinName: 'Vena cava',
    category: 'veins',
    meshKeywords: ['union of brachiocephalic veins', 'systemic veins.j', 'brachiocephalic vein'],
    description: 'cdesc_vena_cava',
    function: 'cfunc_vena_cava',
    clinicalNotes: 'cclin_vena_cava',
    relatedStructures: ['cardio_heart', 'cardio_right_atrium'],
  },
  {
    id: 'cardio_pulmonary_vein',
    name: 'c_pulmonary_vein',
    latinName: 'Vena pulmonalis',
    category: 'veins',
    meshKeywords: ['pulmonary vein', 'superior pulmonary vein', 'inferior pulmonary vein'],
    description: 'cdesc_pulmonary_vein',
    function: 'cfunc_pulmonary_vein',
    clinicalNotes: 'cclin_pulmonary_vein',
    relatedStructures: ['cardio_left_atrium'],
  },
  {
    id: 'cardio_jugular_vein',
    name: 'c_jugular_vein',
    latinName: 'Vena jugularis',
    category: 'veins',
    meshKeywords: ['jugular vein', 'cranial veins.j', 'dural venous sinuses', 'orbital veins'],
    description: 'cdesc_jugular',
    function: 'cfunc_jugular',
    clinicalNotes: 'cclin_jugular',
    relatedStructures: ['cardio_vena_cava'],
  },
  {
    id: 'cardio_lung_veins',
    name: 'c_lung_veins',
    latinName: 'Venae pulmonis',
    category: 'veins',
    meshKeywords: ['vein of left lung', 'vein of right lung', 'lobar vein'],
    description: 'cdesc_pulmonary_vein',
    function: 'cfunc_pulmonary_vein',
    clinicalNotes: 'cclin_pulmonary_vein',
    relatedStructures: ['cardio_pulmonary_vein'],
  },
];
