export const ANATOMY_DB = [
  // SKULL
  {id:'frontal',name:'Frontal Bone',latinName:'Os frontale',category:'skull',cat:'skull',description:'Forms the forehead and the roof of the eye sockets.',fn:'Protects the frontal lobe of the brain and houses the frontal sinuses.'},
  {id:'parietal_r',name:'Parietal Bone (R)',latinName:'Os parietale dextrum',category:'skull',cat:'skull',description:'Forms the top and sides of the skull.',fn:'Protects the parietal lobes of the brain.'},
  {id:'parietal_l',name:'Parietal Bone (L)',latinName:'Os parietale sinistrum',category:'skull',cat:'skull',description:'Forms the top and sides of the skull.',fn:'Protects the parietal lobes of the brain.'},
  {id:'temporal_r',name:'Temporal Bone (R)',latinName:'Os temporale dextrum',category:'skull',cat:'skull',description:'Forms the lower sides and base of the skull.',fn:'Houses the middle and inner ear structures.'},
  {id:'temporal_l',name:'Temporal Bone (L)',latinName:'Os temporale sinistrum',category:'skull',cat:'skull',description:'Forms the lower sides and base of the skull.',fn:'Houses the middle and inner ear structures.'},
  {id:'occipital',name:'Occipital Bone',latinName:'Os occipitale',category:'skull',cat:'skull',description:'Forms the back and base of the cranium.',fn:'Contains the foramen magnum for the spinal cord passage.'},
  {id:'sphenoid',name:'Sphenoid Bone',latinName:'Os sphenoidale',category:'skull',cat:'skull',description:'Butterfly-shaped bone at the base of the skull.',fn:'Articulates with all other cranial bones and forms part of the eye socket floor.'},
  {id:'ethmoid',name:'Ethmoid Bone',latinName:'Os ethmoidale',category:'skull',cat:'skull',description:'Small bone between the eye sockets.',fn:'Forms part of the nasal septum and supports the olfactory nerve.'},
  {id:'nasal_r',name:'Nasal Bone (R)',latinName:'Os nasale dextrum',category:'skull',cat:'skull',description:'Small paired bones forming the bridge of the nose.',fn:'Forms the bony framework of the upper nose.'},
  {id:'nasal_l',name:'Nasal Bone (L)',latinName:'Os nasale sinistrum',category:'skull',cat:'skull',description:'Small paired bones forming the bridge of the nose.',fn:'Forms the bony framework of the upper nose.'},
  {id:'lacrimal_r',name:'Lacrimal Bone (R)',latinName:'Os lacrimale dextrum',category:'skull',cat:'skull',description:'Smallest and most fragile bones of the face.',fn:'Contains the lacrimal fossa, a groove for the lacrimal sac.'},
  {id:'lacrimal_l',name:'Lacrimal Bone (L)',latinName:'Os lacrimale sinistrum',category:'skull',cat:'skull',description:'Smallest and most fragile bones of the face.',fn:'Contains the lacrimal fossa, a groove for the lacrimal sac.'},
  {id:'zygomatic_r',name:'Zygomatic Bone (R)',latinName:'Os zygomaticum dextrum',category:'skull',cat:'skull',description:'The cheekbone.',fn:'Forms the prominence of the cheek and part of the eye socket.'},
  {id:'zygomatic_l',name:'Zygomatic Bone (L)',latinName:'Os zygomaticum sinistrum',category:'skull',cat:'skull',description:'The cheekbone.',fn:'Forms the prominence of the cheek and part of the eye socket.'},
  {id:'maxilla',name:'Maxilla',latinName:'Maxilla',category:'skull',cat:'skull',description:'Upper jaw bone.',fn:'Supports upper teeth and forms the hard palate and floor of the nose.'},
  {id:'mandible',name:'Mandible',latinName:'Mandibula',category:'skull',cat:'skull',description:'The lower jaw — the only movable bone of the skull.',fn:'Supports lower teeth and enables chewing and speech.'},
  {id:'vomer',name:'Vomer',latinName:'Vomer',category:'skull',cat:'skull',description:'Thin flat bone forming the lower nasal septum.',fn:'Divides the nasal cavity into left and right passages.'},
  {id:'palatine_r',name:'Palatine Bone (R)',latinName:'Os palatinum dextrum',category:'skull',cat:'skull',description:'L-shaped bone behind the maxilla.',fn:'Forms the posterior hard palate and floor of the nasal cavity.'},
  {id:'palatine_l',name:'Palatine Bone (L)',latinName:'Os palatinum sinistrum',category:'skull',cat:'skull',description:'L-shaped bone behind the maxilla.',fn:'Forms the posterior hard palate and floor of the nasal cavity.'},
  {id:'inf_nasal_concha_r',name:'Inferior Nasal Concha (R)',latinName:'Concha nasalis inferior dextra',category:'skull',cat:'skull',description:'Curved bone projecting into the nasal cavity.',fn:'Increases nasal surface area for air filtration and humidification.'},
  {id:'inf_nasal_concha_l',name:'Inferior Nasal Concha (L)',latinName:'Concha nasalis inferior sinistra',category:'skull',cat:'skull',description:'Curved bone projecting into the nasal cavity.',fn:'Increases nasal surface area for air filtration and humidification.'},
  // EAR
  {id:'malleus_r',name:'Malleus (R)',latinName:'Malleus dexter',category:'skull',cat:'skull',description:'Hammer-shaped ossicle of the middle ear.',fn:'Transmits vibrations from the eardrum to the incus.'},
  {id:'malleus_l',name:'Malleus (L)',latinName:'Malleus sinister',category:'skull',cat:'skull',description:'Hammer-shaped ossicle of the middle ear.',fn:'Transmits vibrations from the eardrum to the incus.'},
  {id:'incus_r',name:'Incus (R)',latinName:'Incus dexter',category:'skull',cat:'skull',description:'Anvil-shaped ossicle of the middle ear.',fn:'Connects malleus to stapes in the hearing chain.'},
  {id:'incus_l',name:'Incus (L)',latinName:'Incus sinister',category:'skull',cat:'skull',description:'Anvil-shaped ossicle of the middle ear.',fn:'Connects malleus to stapes in the hearing chain.'},
  {id:'stapes_r',name:'Stapes (R)',latinName:'Stapes dexter',category:'skull',cat:'skull',description:'Stirrup-shaped ossicle — smallest bone in the body.',fn:'Transmits vibrations to the oval window of the inner ear.'},
  {id:'stapes_l',name:'Stapes (L)',latinName:'Stapes sinister',category:'skull',cat:'skull',description:'Stirrup-shaped ossicle — smallest bone in the body.',fn:'Transmits vibrations to the oval window of the inner ear.'},
  // HYOID
  {id:'hyoid',name:'Hyoid Bone',latinName:'Os hyoideum',category:'skull',cat:'skull',description:'U-shaped bone at base of tongue.',fn:'Supports the tongue and serves as an attachment for neck muscles.'},
  // VERTEBRAL
  {id:'c1',name:'C1 Atlas',latinName:'Atlas (C1)',category:'vertebral',cat:'vertebral',description:'First cervical vertebra.',fn:'Supports the skull and allows nodding movement.'},
  {id:'c2',name:'C2 Axis',latinName:'Axis (C2)',category:'vertebral',cat:'vertebral',description:'Second cervical vertebra with odontoid process.',fn:'Allows rotation of the head.'},
  {id:'c3',name:'C3 Vertebra',latinName:'Vertebra cervicalis III',category:'vertebral',cat:'vertebral',description:'Third cervical vertebra.',fn:'Supports head and neck movement.'},
  {id:'c4',name:'C4 Vertebra',latinName:'Vertebra cervicalis IV',category:'vertebral',cat:'vertebral',description:'Fourth cervical vertebra.',fn:'Transmits nerve signals to diaphragm.'},
  {id:'c5',name:'C5 Vertebra',latinName:'Vertebra cervicalis V',category:'vertebral',cat:'vertebral',description:'Fifth cervical vertebra.',fn:'Innervates shoulder and biceps muscles.'},
  {id:'c6',name:'C6 Vertebra',latinName:'Vertebra cervicalis VI',category:'vertebral',cat:'vertebral',description:'Sixth cervical vertebra.',fn:'Provides attachment for cervical musculature.'},
  {id:'c7',name:'C7 Vertebra',latinName:'Vertebra prominens',category:'vertebral',cat:'vertebral',description:'Seventh cervical vertebra — most prominent spinous process.',fn:'Transition point between cervical and thoracic spine.'},
  {id:'t1',name:'T1 Vertebra',latinName:'Vertebra thoracica I',category:'vertebral',cat:'vertebral',description:'First thoracic vertebra.',fn:'Articulates with first rib pair.'},
  {id:'t2',name:'T2 Vertebra',latinName:'Vertebra thoracica II',category:'vertebral',cat:'vertebral',description:'Second thoracic vertebra.',fn:'Articulates with second rib pair.'},
  {id:'t3',name:'T3 Vertebra',latinName:'Vertebra thoracica III',category:'vertebral',cat:'vertebral',description:'Third thoracic vertebra.',fn:'Structural support of thoracic cage.'},
  {id:'t4',name:'T4 Vertebra',latinName:'Vertebra thoracica IV',category:'vertebral',cat:'vertebral',description:'Fourth thoracic vertebra.',fn:'Level of sternal angle of Louis.'},
  {id:'t5',name:'T5 Vertebra',latinName:'Vertebra thoracica V',category:'vertebral',cat:'vertebral',description:'Fifth thoracic vertebra.',fn:'Central thoracic spine support.'},
  {id:'t6',name:'T6 Vertebra',latinName:'Vertebra thoracica VI',category:'vertebral',cat:'vertebral',description:'Sixth thoracic vertebra.',fn:'Midpoint of thoracic spine.'},
  {id:'t7',name:'T7 Vertebra',latinName:'Vertebra thoracica VII',category:'vertebral',cat:'vertebral',description:'Seventh thoracic vertebra.',fn:'Inferior thoracic support.'},
  {id:'t8',name:'T8 Vertebra',latinName:'Vertebra thoracica VIII',category:'vertebral',cat:'vertebral',description:'Eighth thoracic vertebra.',fn:'Supports thoracic cage.'},
  {id:'t9',name:'T9 Vertebra',latinName:'Vertebra thoracica IX',category:'vertebral',cat:'vertebral',description:'Ninth thoracic vertebra.',fn:'Lower thoracic stability.'},
  {id:'t10',name:'T10 Vertebra',latinName:'Vertebra thoracica X',category:'vertebral',cat:'vertebral',description:'Tenth thoracic vertebra.',fn:'Transitional thoracolumbar region.'},
  {id:'t11',name:'T11 Vertebra',latinName:'Vertebra thoracica XI',category:'vertebral',cat:'vertebral',description:'Eleventh thoracic vertebra — floating rib attachment.',fn:'Articulates with floating ribs.'},
  {id:'t12',name:'T12 Vertebra',latinName:'Vertebra thoracica XII',category:'vertebral',cat:'vertebral',description:'Twelfth thoracic vertebra.',fn:'Last floating rib attachment point.'},
  {id:'l1',name:'L1 Vertebra',latinName:'Vertebra lumbalis I',category:'vertebral',cat:'vertebral',description:'First lumbar vertebra.',fn:'Transmits weight to lower spine.'},
  {id:'l2',name:'L2 Vertebra',latinName:'Vertebra lumbalis II',category:'vertebral',cat:'vertebral',description:'Second lumbar vertebra.',fn:'Supports trunk weight.'},
  {id:'l3',name:'L3 Vertebra',latinName:'Vertebra lumbalis III',category:'vertebral',cat:'vertebral',description:'Third lumbar vertebra.',fn:'Central lumbar weight bearing.'},
  {id:'l4',name:'L4 Vertebra',latinName:'Vertebra lumbalis IV',category:'vertebral',cat:'vertebral',description:'Fourth lumbar vertebra.',fn:'Major weight-bearing vertebra; L4-L5 disc commonly affected.'},
  {id:'l5',name:'L5 Vertebra',latinName:'Vertebra lumbalis V',category:'vertebral',cat:'vertebral',description:'Fifth lumbar vertebra — most common disc herniation site.',fn:'Transmits body weight to sacrum.'},
  {id:'sacrum',name:'Sacrum',latinName:'Os sacrum',category:'vertebral',cat:'vertebral',description:'Triangular bone composed of 5 fused sacral vertebrae.',fn:'Transfers trunk weight to pelvis; sacroiliac joint.'},
  {id:'coccyx',name:'Coccyx',latinName:'Os coccygis',category:'vertebral',cat:'vertebral',description:'Tailbone — 3-5 fused coccygeal vertebrae.',fn:'Attachment for pelvic floor muscles and ligaments.'},
  // THORAX
  {id:'manubrium',name:'Manubrium',latinName:'Manubrium sterni',category:'thorax',cat:'thorax',description:'Upper part of the sternum.',fn:'Articulates with clavicles and first two ribs.'},
  {id:'sternum_body',name:'Body of Sternum',latinName:'Corpus sterni',category:'thorax',cat:'thorax',description:'Long flat middle section of the sternum.',fn:'Articulates with ribs 3–7 via costal cartilages.'},
  {id:'xiphoid',name:'Xiphoid Process',latinName:'Processus xiphoideus',category:'thorax',cat:'thorax',description:'Small inferior process of the sternum.',fn:'Muscle attachment for diaphragm and abdominal muscles.'},
  ...[...Array(12)].map((_,i)=>({
    id:`rib_r${i+1}`,name:`Rib ${i+1} (R)`,latinName:`Costa ${['I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII'][i]} dextra`,
    category:'thorax',cat:'thorax',
    description: i<7 ? `True rib — connects directly to sternum via costal cartilage.` : i<10 ? `False rib — connects to sternum indirectly.` : `Floating rib — no anterior attachment.`,
    fn: `Protects thoracic organs; assists respiration.`
  })),
  ...[...Array(12)].map((_,i)=>({
    id:`rib_l${i+1}`,name:`Rib ${i+1} (L)`,latinName:`Costa ${['I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII'][i]} sinistra`,
    category:'thorax',cat:'thorax',
    description: i<7 ? `True rib — connects directly to sternum via costal cartilage.` : i<10 ? `False rib — connects to sternum indirectly.` : `Floating rib — no anterior attachment.`,
    fn:`Protects thoracic organs; assists respiration.`
  })),
  // PECTORAL GIRDLE
  {id:'clavicle_r',name:'Clavicle (R)',latinName:'Clavicula dextra',category:'upper',cat:'upper',description:'S-shaped collarbone.',fn:'Transmits forces from arm to axial skeleton; keeps arm away from trunk.'},
  {id:'clavicle_l',name:'Clavicle (L)',latinName:'Clavicula sinistra',category:'upper',cat:'upper',description:'S-shaped collarbone.',fn:'Transmits forces from arm to axial skeleton; keeps arm away from trunk.'},
  {id:'scapula_r',name:'Scapula (R)',latinName:'Scapula dextra',category:'upper',cat:'upper',description:'Shoulder blade — triangular flat bone.',fn:'Connects arm to clavicle; attachment for 17 muscles.'},
  {id:'scapula_l',name:'Scapula (L)',latinName:'Scapula sinistra',category:'upper',cat:'upper',description:'Shoulder blade — triangular flat bone.',fn:'Connects arm to clavicle; attachment for 17 muscles.'},
  // UPPER LIMBS
  {id:'humerus_r',name:'Humerus (R)',latinName:'Humerus dexter',category:'upper',cat:'upper',description:'Long bone of the upper arm.',fn:'Connects shoulder to elbow; attachment for arm and shoulder muscles.'},
  {id:'humerus_l',name:'Humerus (L)',latinName:'Humerus sinister',category:'upper',cat:'upper',description:'Long bone of the upper arm.',fn:'Connects shoulder to elbow; attachment for arm and shoulder muscles.'},
  {id:'radius_r',name:'Radius (R)',latinName:'Radius dexter',category:'upper',cat:'upper',description:'Lateral forearm bone (thumb side).',fn:'Primary rotation bone of the forearm; articulates with carpals.'},
  {id:'radius_l',name:'Radius (L)',latinName:'Radius sinister',category:'upper',cat:'upper',description:'Lateral forearm bone (thumb side).',fn:'Primary rotation bone of the forearm; articulates with carpals.'},
  {id:'ulna_r',name:'Ulna (R)',latinName:'Ulna dextra',category:'upper',cat:'upper',description:'Medial forearm bone (pinky side).',fn:'Forms elbow joint; stability in forearm rotation.'},
  {id:'ulna_l',name:'Ulna (L)',latinName:'Ulna sinistra',category:'upper',cat:'upper',description:'Medial forearm bone (pinky side).',fn:'Forms elbow joint; stability in forearm rotation.'},
  // CARPALS R
  {id:'scaphoid_r',name:'Scaphoid (R)',latinName:'Os scaphoideum dextrum',category:'hand',cat:'hand',description:'Boat-shaped carpal bone.',fn:'Key carpal in wrist movement; most commonly fractured wrist bone.'},
  {id:'lunate_r',name:'Lunate (R)',latinName:'Os lunatum dextrum',category:'hand',cat:'hand',description:'Moon-shaped carpal bone.',fn:'Central wrist joint motion.'},
  {id:'triquetrum_r',name:'Triquetrum (R)',latinName:'Os triquetrum dextrum',category:'hand',cat:'hand',description:'Three-cornered carpal bone.',fn:'Assists wrist ulnar deviation.'},
  {id:'pisiform_r',name:'Pisiform (R)',latinName:'Os pisiforme dextrum',category:'hand',cat:'hand',description:'Pea-shaped sesamoid carpal bone.',fn:'Acts as a pulley for the flexor carpi ulnaris tendon.'},
  {id:'trapezium_r',name:'Trapezium (R)',latinName:'Os trapezium dextrum',category:'hand',cat:'hand',description:'Carpal bone at the base of the thumb.',fn:'Forms the carpometacarpal joint of the thumb.'},
  {id:'trapezoid_r',name:'Trapezoid (R)',latinName:'Os trapezoideum dextrum',category:'hand',cat:'hand',description:'Small wedge-shaped carpal bone.',fn:'Stabilizes the index finger metacarpal.'},
  {id:'capitate_r',name:'Capitate (R)',latinName:'Os capitatum dextrum',category:'hand',cat:'hand',description:'Largest carpal bone.',fn:'Central pivot of the wrist complex.'},
  {id:'hamate_r',name:'Hamate (R)',latinName:'Os hamatum dextrum',category:'hand',cat:'hand',description:'Wedge-shaped carpal bone with hooked process.',fn:'Attachment for hypothenar muscles.'},
  // CARPALS L
  {id:'scaphoid_l',name:'Scaphoid (L)',latinName:'Os scaphoideum sinistrum',category:'hand',cat:'hand',description:'Boat-shaped carpal bone.',fn:'Key carpal in wrist movement; most commonly fractured wrist bone.'},
  {id:'lunate_l',name:'Lunate (L)',latinName:'Os lunatum sinistrum',category:'hand',cat:'hand',description:'Moon-shaped carpal bone.',fn:'Central wrist joint motion.'},
  {id:'triquetrum_l',name:'Triquetrum (L)',latinName:'Os triquetrum sinistrum',category:'hand',cat:'hand',description:'Three-cornered carpal bone.',fn:'Assists wrist ulnar deviation.'},
  {id:'pisiform_l',name:'Pisiform (L)',latinName:'Os pisiforme sinistrum',category:'hand',cat:'hand',description:'Pea-shaped sesamoid carpal bone.',fn:'Acts as a pulley for the flexor carpi ulnaris tendon.'},
  {id:'trapezium_l',name:'Trapezium (L)',latinName:'Os trapezium sinistrum',category:'hand',cat:'hand',description:'Carpal bone at the base of the thumb.',fn:'Forms the carpometacarpal joint of the thumb.'},
  {id:'trapezoid_l',name:'Trapezoid (L)',latinName:'Os trapezoideum sinistrum',category:'hand',cat:'hand',description:'Small wedge-shaped carpal bone.',fn:'Stabilizes the index finger metacarpal.'},
  {id:'capitate_l',name:'Capitate (L)',latinName:'Os capitatum sinistrum',category:'hand',cat:'hand',description:'Largest carpal bone.',fn:'Central pivot of the wrist complex.'},
  {id:'hamate_l',name:'Hamate (L)',latinName:'Os hamatum sinistrum',category:'hand',cat:'hand',description:'Wedge-shaped carpal bone with hooked process.',fn:'Attachment for hypothenar muscles.'},
  // METACARPALS + PHALANGES - Right hand
  ...[...Array(5)].map((_,i)=>({id:`mc_r${i+1}`,name:`Metacarpal ${i+1} (R)`,latinName:`Os metacarpale ${['I','II','III','IV','V'][i]} dextrum`,category:'hand',cat:'hand',description:`Metacarpal bone of the ${['thumb','index','middle','ring','little'][i]} finger.`,fn:'Forms the palm; transmits grip force.'})),
  ...[...Array(5)].map((_,i)=>({id:`mc_l${i+1}`,name:`Metacarpal ${i+1} (L)`,latinName:`Os metacarpale ${['I','II','III','IV','V'][i]} sinistrum`,category:'hand',cat:'hand',description:`Metacarpal bone of the ${['thumb','index','middle','ring','little'][i]} finger.`,fn:'Forms the palm; transmits grip force.'})),
  // Proximal phalanges right
  ...[...Array(5)].map((_,i)=>({id:`pp_r${i+1}`,name:`Proximal Phalanx ${i+1} (R)`,latinName:`Phalanx proximalis digiti ${['I','II','III','IV','V'][i]} dextri`,category:'hand',cat:'hand',description:'Proximal finger bone.',fn:'Forms the base of each finger.'})),
  ...[...Array(5)].map((_,i)=>({id:`mp_r${i+1}`,name:`Middle Phalanx ${i+1} (R)`,latinName:`Phalanx media digiti ${['II','III','IV','V'][i>0?i-1:0]} dextri`,category:'hand',cat:'hand',description:'Middle finger bone (absent in thumb).',fn:'Allows finger flexion and extension.'})),
  ...[...Array(5)].map((_,i)=>({id:`dp_r${i+1}`,name:`Distal Phalanx ${i+1} (R)`,latinName:`Phalanx distalis digiti ${['I','II','III','IV','V'][i]} dextri`,category:'hand',cat:'hand',description:'Fingertip bone.',fn:'Supports fingernail and fine motor function.'})),
  // Phalanges left
  ...[...Array(5)].map((_,i)=>({id:`pp_l${i+1}`,name:`Proximal Phalanx ${i+1} (L)`,latinName:`Phalanx proximalis digiti ${['I','II','III','IV','V'][i]} sinistri`,category:'hand',cat:'hand',description:'Proximal finger bone.',fn:'Forms the base of each finger.'})),
  ...[...Array(5)].map((_,i)=>({id:`mp_l${i+1}`,name:`Middle Phalanx ${i+1} (L)`,latinName:`Phalanx media digiti ${['II','III','IV','V'][i>0?i-1:0]} sinistri`,category:'hand',cat:'hand',description:'Middle finger bone.',fn:'Allows finger flexion and extension.'})),
  ...[...Array(5)].map((_,i)=>({id:`dp_l${i+1}`,name:`Distal Phalanx ${i+1} (L)`,latinName:`Phalanx distalis digiti ${['I','II','III','IV','V'][i]} sinistri`,category:'hand',cat:'hand',description:'Fingertip bone.',fn:'Supports fingernail and fine motor function.'})),
  // PELVIS
  {id:'ilium_r',name:'Ilium (R)',latinName:'Os ilium dextrum',category:'pelvis',cat:'pelvis',description:'Large fan-shaped upper hip bone.',fn:'Transmits trunk weight to legs; attachment for gluteal muscles.'},
  {id:'ilium_l',name:'Ilium (L)',latinName:'Os ilium sinistrum',category:'pelvis',cat:'pelvis',description:'Large fan-shaped upper hip bone.',fn:'Transmits trunk weight to legs; attachment for gluteal muscles.'},
  {id:'ischium_r',name:'Ischium (R)',latinName:'Os ischii dextrum',category:'pelvis',cat:'pelvis',description:'Lower posterior hip bone.',fn:'Supports body weight when sitting; hamstring attachment.'},
  {id:'ischium_l',name:'Ischium (L)',latinName:'Os ischii sinistrum',category:'pelvis',cat:'pelvis',description:'Lower posterior hip bone.',fn:'Supports body weight when sitting; hamstring attachment.'},
  {id:'pubis_r',name:'Pubis (R)',latinName:'Os pubis dextrum',category:'pelvis',cat:'pelvis',description:'Anterior lower hip bone.',fn:'Forms the pubic symphysis; inner thigh muscle attachment.'},
  {id:'pubis_l',name:'Pubis (L)',latinName:'Os pubis sinistrum',category:'pelvis',cat:'pelvis',description:'Anterior lower hip bone.',fn:'Forms the pubic symphysis; inner thigh muscle attachment.'},
  // LOWER LIMBS
  {id:'femur_r',name:'Femur (R)',latinName:'Os femoris dextrum',category:'lower',cat:'lower',description:'Longest and strongest bone in the body.',fn:'Supports body weight; enables hip and knee movement.'},
  {id:'femur_l',name:'Femur (L)',latinName:'Os femoris sinistrum',category:'lower',cat:'lower',description:'Longest and strongest bone in the body.',fn:'Supports body weight; enables hip and knee movement.'},
  {id:'patella_r',name:'Patella (R)',latinName:'Patella dextra',category:'lower',cat:'lower',description:'Kneecap — largest sesamoid bone.',fn:'Protects knee joint; improves quadriceps leverage.'},
  {id:'patella_l',name:'Patella (L)',latinName:'Patella sinistra',category:'lower',cat:'lower',description:'Kneecap — largest sesamoid bone.',fn:'Protects knee joint; improves quadriceps leverage.'},
  {id:'tibia_r',name:'Tibia (R)',latinName:'Tibia dextra',category:'lower',cat:'lower',description:'Shinbone — second largest bone in the body.',fn:'Primary weight-bearing lower leg bone; forms knee and ankle joints.'},
  {id:'tibia_l',name:'Tibia (L)',latinName:'Tibia sinistra',category:'lower',cat:'lower',description:'Shinbone — second largest bone in the body.',fn:'Primary weight-bearing lower leg bone; forms knee and ankle joints.'},
  {id:'fibula_r',name:'Fibula (R)',latinName:'Fibula dextra',category:'lower',cat:'lower',description:'Slender lateral lower leg bone.',fn:'Stabilizes ankle; muscle attachment for lower leg.'},
  {id:'fibula_l',name:'Fibula (L)',latinName:'Fibula sinistra',category:'lower',cat:'lower',description:'Slender lateral lower leg bone.',fn:'Stabilizes ankle; muscle attachment for lower leg.'},
  // FOOT
  {id:'calcaneus_r',name:'Calcaneus (R)',latinName:'Calcaneus dexter',category:'foot',cat:'foot',description:'Heel bone — largest tarsal.',fn:'Transmits body weight to ground; Achilles tendon attachment.'},
  {id:'calcaneus_l',name:'Calcaneus (L)',latinName:'Calcaneus sinister',category:'foot',cat:'foot',description:'Heel bone — largest tarsal.',fn:'Transmits body weight to ground; Achilles tendon attachment.'},
  {id:'talus_r',name:'Talus (R)',latinName:'Talus dexter',category:'foot',cat:'foot',description:'Ankle bone connecting foot to leg.',fn:'Transmits body weight from tibia to foot.'},
  {id:'talus_l',name:'Talus (L)',latinName:'Talus sinister',category:'foot',cat:'foot',description:'Ankle bone connecting foot to leg.',fn:'Transmits body weight from tibia to foot.'},
  {id:'navicular_r',name:'Navicular (R)',latinName:'Os naviculare dextrum',category:'foot',cat:'foot',description:'Boat-shaped tarsal on medial foot.',fn:'Supports medial arch of the foot.'},
  {id:'navicular_l',name:'Navicular (L)',latinName:'Os naviculare sinistrum',category:'foot',cat:'foot',description:'Boat-shaped tarsal on medial foot.',fn:'Supports medial arch of the foot.'},
  {id:'cuboid_r',name:'Cuboid (R)',latinName:'Os cuboideum dextrum',category:'foot',cat:'foot',description:'Cube-shaped lateral tarsal bone.',fn:'Supports lateral arch of the foot.'},
  {id:'cuboid_l',name:'Cuboid (L)',latinName:'Os cuboideum sinistrum',category:'foot',cat:'foot',description:'Cube-shaped lateral tarsal bone.',fn:'Supports lateral arch of the foot.'},
  {id:'cuneiform1_r',name:'Medial Cuneiform (R)',latinName:'Os cuneiforme mediale dextrum',category:'foot',cat:'foot',description:'First and largest cuneiform.',fn:'Base for first metatarsal articulation.'},
  {id:'cuneiform1_l',name:'Medial Cuneiform (L)',latinName:'Os cuneiforme mediale sinistrum',category:'foot',cat:'foot',description:'First and largest cuneiform.',fn:'Base for first metatarsal articulation.'},
  {id:'cuneiform2_r',name:'Intermediate Cuneiform (R)',latinName:'Os cuneiforme intermedium dextrum',category:'foot',cat:'foot',description:'Smallest and most deeply wedged cuneiform.',fn:'Base for second metatarsal.'},
  {id:'cuneiform2_l',name:'Intermediate Cuneiform (L)',latinName:'Os cuneiforme intermedium sinistrum',category:'foot',cat:'foot',description:'Smallest cuneiform.',fn:'Base for second metatarsal.'},
  {id:'cuneiform3_r',name:'Lateral Cuneiform (R)',latinName:'Os cuneiforme laterale dextrum',category:'foot',cat:'foot',description:'Third cuneiform on lateral midfoot.',fn:'Base for third metatarsal.'},
  {id:'cuneiform3_l',name:'Lateral Cuneiform (L)',latinName:'Os cuneiforme laterale sinistrum',category:'foot',cat:'foot',description:'Third cuneiform on lateral midfoot.',fn:'Base for third metatarsal.'},
  ...[...Array(5)].map((_,i)=>({id:`mt_r${i+1}`,name:`Metatarsal ${i+1} (R)`,latinName:`Os metatarsale ${['I','II','III','IV','V'][i]} dextrum`,category:'foot',cat:'foot',description:`Foot metacarpal ${i+1}.`,fn:'Forms foot arch; transmits body weight.'})),
  ...[...Array(5)].map((_,i)=>({id:`mt_l${i+1}`,name:`Metatarsal ${i+1} (L)`,latinName:`Os metatarsale ${['I','II','III','IV','V'][i]} sinistrum`,category:'foot',cat:'foot',description:`Foot metacarpal ${i+1}.`,fn:'Forms foot arch; transmits body weight.'})),
  ...[...Array(5)].map((_,i)=>({id:`toe_pp_r${i+1}`,name:`Toe Proximal Phalanx ${i+1} (R)`,latinName:`Phalanx proximalis pedis ${['I','II','III','IV','V'][i]} dextri`,category:'foot',cat:'foot',description:'Proximal toe bone.',fn:'Enables toe flexion for balance and propulsion.'})),
  ...[...Array(4)].map((_,i)=>({id:`toe_mp_r${i+1}`,name:`Toe Middle Phalanx ${i+2} (R)`,latinName:`Phalanx media pedis ${['II','III','IV','V'][i]} dextri`,category:'foot',cat:'foot',description:'Middle toe bone.',fn:'Enables toe bending for balance.'})),
  ...[...Array(5)].map((_,i)=>({id:`toe_dp_r${i+1}`,name:`Toe Distal Phalanx ${i+1} (R)`,latinName:`Phalanx distalis pedis ${['I','II','III','IV','V'][i]} dextri`,category:'foot',cat:'foot',description:'Toenail support bone.',fn:'Ground contact; toenail bed support.'})),
  ...[...Array(5)].map((_,i)=>({id:`toe_pp_l${i+1}`,name:`Toe Proximal Phalanx ${i+1} (L)`,latinName:`Phalanx proximalis pedis ${['I','II','III','IV','V'][i]} sinistri`,category:'foot',cat:'foot',description:'Proximal toe bone.',fn:'Enables toe flexion for balance and propulsion.'})),
  ...[...Array(4)].map((_,i)=>({id:`toe_mp_l${i+1}`,name:`Toe Middle Phalanx ${i+2} (L)`,latinName:`Phalanx media pedis ${['II','III','IV','V'][i]} sinistri`,category:'foot',cat:'foot',description:'Middle toe bone.',fn:'Enables toe bending for balance.'})),
  ...[...Array(5)].map((_,i)=>({id:`toe_dp_l${i+1}`,name:`Toe Distal Phalanx ${i+1} (L)`,latinName:`Phalanx distalis pedis ${['I','II','III','IV','V'][i]} sinistri`,category:'foot',cat:'foot',description:'Toenail support bone.',fn:'Ground contact; toenail bed support.'})),
];