export const MUSCLE_DB = [
  // ─── HEAD MUSCLES ──────────────────────────────────────────────────────────
  {
    id: 'frontalis', name: 'Frontalis', latinName: 'Musculus frontalis', category: 'head',
    origin: 'Galea aponeurotica (epicranial aponeurosis)',
    insertion: 'Skin of the forehead and eyebrows',
    function: 'Raises the eyebrows, wrinkles the forehead, assists in opening the eyes wide',
    innervation: 'Facial nerve (CN VII) — temporal branch',
    bloodSupply: 'Supratrochlear and supraorbital arteries (from ophthalmic artery)',
    clinicalNotes: 'Paralysis (Bell\'s palsy) prevents brow raising. Botulinum toxin commonly injected here for cosmetic wrinkle reduction. Frontalis tension-type headaches common.',
    originBones: ['frontal'], insertionBones: ['frontal'],
  },
  {
    id: 'orbicularis_oculi', name: 'Orbicularis Oculi', latinName: 'Musculus orbicularis oculi', category: 'head',
    origin: 'Medial orbital margin, medial palpebral ligament, lacrimal bone',
    insertion: 'Skin and orbicularis of eyelid, lateral palpebral raphe',
    function: 'Closes the eyelids (blinking, squinting, forceful closure)',
    innervation: 'Facial nerve (CN VII) — temporal and zygomatic branches',
    bloodSupply: 'Facial artery, supraorbital and infraorbital arteries',
    clinicalNotes: 'Paralysis leads to lagophthalmos (inability to close eye), corneal exposure, and dryness. Blepharospasm (involuntary spasm) treated with botulinum toxin.',
    originBones: ['lacrimal_r', 'lacrimal_l'], insertionBones: ['frontal', 'zygomatic_r', 'zygomatic_l'],
  },
  {
    id: 'orbicularis_oris', name: 'Orbicularis Oris', latinName: 'Musculus orbicularis oris', category: 'head',
    origin: 'Fibers from adjacent facial muscles converging around the mouth',
    insertion: 'Mucosa and skin at the margins of the lips',
    function: 'Closes and protrudes lips; essential for speech, kissing, and sucking',
    innervation: 'Facial nerve (CN VII) — buccal and marginal mandibular branches',
    bloodSupply: 'Superior and inferior labial arteries (branches of facial artery)',
    clinicalNotes: 'Paralysis impairs speech and eating. Cleft lip involves abnormal muscle insertion across the cleft. Whistler\'s muscle — critical for trumpet playing.',
    originBones: ['maxilla', 'mandible'], insertionBones: ['maxilla', 'mandible'],
  },
  {
    id: 'masseter', name: 'Masseter', latinName: 'Musculus masseter', category: 'head',
    origin: 'Zygomatic arch (lower border and medial surface)',
    insertion: 'Angle and ramus of the mandible (lateral surface)',
    function: 'Elevates (closes) the mandible; most powerful chewing muscle',
    innervation: 'Trigeminal nerve (CN V3) — masseteric nerve',
    bloodSupply: 'Masseteric artery (from maxillary artery), facial artery',
    clinicalNotes: 'Hypertrophy causes facial widening and bruxism. Masseter abscess from dental infections. Botox injection reduces jaw grinding. Palpable at angle of jaw when clenching teeth.',
    originBones: ['zygomatic_r', 'zygomatic_l'], insertionBones: ['mandible'],
  },
  {
    id: 'temporalis', name: 'Temporalis', latinName: 'Musculus temporalis', category: 'head',
    origin: 'Temporal fossa (floor) and temporal fascia',
    insertion: 'Coronoid process and anterior ramus of mandible',
    function: 'Elevates (closes) mandible; posterior fibers retract (retrude) mandible',
    innervation: 'Trigeminal nerve (CN V3) — deep temporal nerves',
    bloodSupply: 'Deep temporal arteries (from maxillary artery)',
    clinicalNotes: 'Temporal tendinitis causes jaw pain radiating to temple. Temporomandibular joint disorders often involve temporalis spasm. Used in temporalis transfer surgery for facial reanimation.',
    originBones: ['temporal_r', 'temporal_l', 'parietal_r', 'parietal_l'], insertionBones: ['mandible'],
  },
  {
    id: 'zygomaticus_major', name: 'Zygomaticus Major', latinName: 'Musculus zygomaticus major', category: 'head',
    origin: 'Zygomatic bone (lateral surface)',
    insertion: 'Modiolus (angle of mouth)',
    function: 'Draws angle of mouth superiorly and laterally (smiling)',
    innervation: 'Facial nerve (CN VII) — zygomatic and buccal branches',
    bloodSupply: 'Facial artery and its branches',
    clinicalNotes: 'Key muscle for genuine (Duchenne) smile. Asymmetry indicates facial nerve pathology. Surgically used in smile reanimation procedures.',
    originBones: ['zygomatic_r', 'zygomatic_l'], insertionBones: ['mandible'],
  },
  {
    id: 'buccinator', name: 'Buccinator', latinName: 'Musculus buccinator', category: 'head',
    origin: 'Alveolar processes of maxilla and mandible; pterygomandibular raphe',
    insertion: 'Orbicularis oris and modiolus at angle of mouth',
    function: 'Compresses cheeks (keeps food between teeth during chewing); blowing',
    innervation: 'Facial nerve (CN VII) — buccal branches',
    bloodSupply: 'Buccal artery (from maxillary artery), facial artery',
    clinicalNotes: 'Paralysis leads to food accumulation between cheek and teeth. Parotid duct (Stensen\'s duct) pierces this muscle. Important in infants for suckling.',
    originBones: ['maxilla', 'mandible'], insertionBones: ['maxilla', 'mandible'],
  },
  {
    id: 'platysma', name: 'Platysma', latinName: 'Musculus platysma', category: 'head',
    origin: 'Skin and fascia over pectoralis major and deltoid',
    insertion: 'Mandible, skin of cheek, and orbicularis oris',
    function: 'Depresses mandible and lower lip; tenses neck skin; assists in grimacing',
    innervation: 'Facial nerve (CN VII) — cervical branch',
    bloodSupply: 'Submental artery, suprascapular artery',
    clinicalNotes: 'Prominent "platysmal bands" in neck with age — addressed in facelift surgery. Platysma visible during forced jaw opening against resistance.',
    originBones: ['mandible'], insertionBones: ['clavicle_r', 'clavicle_l'],
  },
  // ─── NECK MUSCLES ─────────────────────────────────────────────────────────
  {
    id: 'sternocleidomastoid', name: 'Sternocleidomastoid', latinName: 'Musculus sternocleidomastoideus', category: 'neck',
    origin: 'Sternal head: manubrium sterni. Clavicular head: medial third of clavicle',
    insertion: 'Mastoid process of temporal bone; lateral half of superior nuchal line',
    function: 'Unilateral: rotates head to opposite side, tilts to same side. Bilateral: flexes neck, raises sternum in forced inspiration',
    innervation: 'Accessory nerve (CN XI) + C2–C3 cervical plexus (proprioception)',
    bloodSupply: 'Occipital artery, superior thyroid artery, suprascapular artery',
    clinicalNotes: 'Torticollis (wry neck): spasm causing head tilt to one side. Congenital muscular torticollis from birth injury. Palpable as diagonal neck cord. Landmark for carotid triangle and posterior cervical triangle.',
    originBones: ['manubrium', 'clavicle_r', 'clavicle_l'], insertionBones: ['temporal_r', 'temporal_l', 'occipital'],
  },
  {
    id: 'scalene_anterior', name: 'Anterior Scalene', latinName: 'Musculus scalenus anterior', category: 'neck',
    origin: 'Anterior tubercles of transverse processes of C3–C6',
    insertion: 'Scalene tubercle on first rib',
    function: 'Elevates first rib; flexes and laterally bends neck',
    innervation: 'Cervical plexus C4–C6',
    bloodSupply: 'Inferior thyroid artery, ascending cervical artery',
    clinicalNotes: 'Thoracic outlet syndrome — subclavian artery and brachial plexus pass between anterior and middle scalene. Scalenotomy performed for thoracic outlet syndrome relief.',
    originBones: ['c3', 'c4', 'c5', 'c6'], insertionBones: ['rib_r1', 'rib_l1'],
  },
  {
    id: 'scalene_middle', name: 'Middle Scalene', latinName: 'Musculus scalenus medius', category: 'neck',
    origin: 'Posterior tubercles of transverse processes of C2–C7',
    insertion: 'Superior surface of first rib (posterior to scalene tubercle)',
    function: 'Elevates first rib; laterally flexes cervical spine',
    innervation: 'Ventral rami C3–C8',
    bloodSupply: 'Ascending cervical artery, deep cervical artery',
    clinicalNotes: 'Largest of the scalene muscles. Long thoracic nerve (C5–C7) passes through or behind middle scalene. Nerve block for brachial plexus anesthesia targets this region.',
    originBones: ['c2', 'c3', 'c4', 'c5', 'c6', 'c7'], insertionBones: ['rib_r1', 'rib_l1'],
  },
  {
    id: 'splenius_capitis', name: 'Splenius Capitis', latinName: 'Musculus splenius capitis', category: 'neck',
    origin: 'Nuchal ligament and spinous processes of C7–T4',
    insertion: 'Mastoid process and lateral third of superior nuchal line',
    function: 'Extends head; unilateral: ipsilateral rotation and lateral flexion of head',
    innervation: 'Dorsal rami of middle cervical nerves (C3–C5)',
    bloodSupply: 'Occipital artery, deep cervical artery',
    clinicalNotes: 'Often involved in tension-type headaches and whiplash injuries. Tender points at mastoid insertion in cervicogenic headache.',
    originBones: ['c7', 't1', 't2', 't3', 't4'], insertionBones: ['temporal_r', 'temporal_l', 'occipital'],
  },
  {
    id: 'levator_scapulae', name: 'Levator Scapulae', latinName: 'Musculus levator scapulae', category: 'neck',
    origin: 'Transverse processes of C1–C4',
    insertion: 'Medial border of scapula (superior angle)',
    function: 'Elevates scapula; rotates glenoid inferiorly; laterally flexes neck',
    innervation: 'Dorsal scapular nerve (C5) + direct branches from C3–C4',
    bloodSupply: 'Dorsal scapular artery, ascending cervical artery',
    clinicalNotes: 'Common source of neck and shoulder pain ("stiff neck"). Frequently in spasm with prolonged desk work. Trigger points cause pain radiating to shoulder.',
    originBones: ['c1', 'c2', 'c3', 'c4'], insertionBones: ['scapula_r', 'scapula_l'],
  },
  {
    id: 'longus_colli', name: 'Longus Colli', latinName: 'Musculus longus colli', category: 'neck',
    origin: 'Anterior surfaces of C1–C3 vertebrae, T1–T3 bodies, transverse processes of C3–C5',
    insertion: 'Anterior arch of atlas, transverse processes of C5–C6, anterior bodies of C2–C4',
    function: 'Flexes cervical spine; slight rotation to same side',
    innervation: 'Ventral rami C2–C8',
    bloodSupply: 'Inferior thyroid artery, ascending cervical artery',
    clinicalNotes: 'Calcific tendinitis at C1–C2 attachment causes acute neck pain and torticollis (crowned dens syndrome). Prevertebral hematoma may compress esophagus. Deep cervical prevertebral muscle.',
    originBones: ['c1', 'c2', 'c3', 't1', 't2', 't3'], insertionBones: ['c1', 'c2', 'c3', 'c4', 'c5', 'c6'],
  },
  // ─── BACK MUSCLES ──────────────────────────────────────────────────────────
  {
    id: 'trapezius', name: 'Trapezius', latinName: 'Musculus trapezius', category: 'back',
    origin: 'External occipital protuberance, nuchal ligament, spinous processes of C7–T12',
    insertion: 'Upper: lateral third of clavicle. Middle: acromion, spine of scapula. Lower: spine of scapula',
    function: 'Upper: elevates scapula and shoulder. Middle: retracts scapula. Lower: depresses scapula. All parts rotate glenoid superiorly (overhead reach)',
    innervation: 'Accessory nerve (CN XI) + C3–C4 ventral rami (proprioception)',
    bloodSupply: 'Transverse cervical artery, occipital artery',
    clinicalNotes: 'CN XI damage (neck surgery, lymph node biopsy) causes winged scapula and shoulder drop. Trapezius trigger points cause "coat hanger" pain pattern. Largest superficial back muscle.',
    originBones: ['occipital', 'c7', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't12'], insertionBones: ['clavicle_r', 'clavicle_l', 'scapula_r', 'scapula_l'],
  },
  {
    id: 'latissimus_dorsi', name: 'Latissimus Dorsi', latinName: 'Musculus latissimus dorsi', category: 'back',
    origin: 'Spinous processes T7–T12, thoracolumbar fascia (L1–L5 and sacrum), posterior iliac crest, inferior 3–4 ribs',
    insertion: 'Intertubercular groove of humerus (floor)',
    function: 'Adducts, extends, and medially rotates humerus ("swimmer\'s muscle"); depresses shoulder girdle',
    innervation: 'Thoracodorsal nerve (C6–C8)',
    bloodSupply: 'Thoracodorsal artery (from subscapular artery)',
    clinicalNotes: 'Commonly used in reconstructive flaps (latissimus dorsi flap) for breast reconstruction after mastectomy or coverage of back wounds. Key muscle for swimming (backstroke), climbing, rowing.',
    originBones: ['t7', 't8', 't9', 't10', 't11', 't12', 'l1', 'l2', 'l3', 'l4', 'l5', 'sacrum', 'ilium_r', 'ilium_l'], insertionBones: ['humerus_r', 'humerus_l'],
  },
  {
    id: 'rhomboid_major', name: 'Rhomboid Major', latinName: 'Musculus rhomboideus major', category: 'back',
    origin: 'Spinous processes of T2–T5',
    insertion: 'Medial border of scapula (between spine and inferior angle)',
    function: 'Retracts scapula; rotates glenoid inferiorly; elevates medial border of scapula',
    innervation: 'Dorsal scapular nerve (C4–C5)',
    bloodSupply: 'Dorsal scapular artery',
    clinicalNotes: 'Weakness causes medial scapular winging. Rhomboid strain common with prolonged forward-head posture and desk work. Dorsal scapular nerve entrapment causes inter-scapular pain.',
    originBones: ['t2', 't3', 't4', 't5'], insertionBones: ['scapula_r', 'scapula_l'],
  },
  {
    id: 'rhomboid_minor', name: 'Rhomboid Minor', latinName: 'Musculus rhomboideus minor', category: 'back',
    origin: 'Nuchal ligament and spinous processes of C7–T1',
    insertion: 'Medial border of scapula (at level of scapular spine)',
    function: 'Retracts and elevates scapula; rotates glenoid inferiorly',
    innervation: 'Dorsal scapular nerve (C4–C5)',
    bloodSupply: 'Dorsal scapular artery',
    clinicalNotes: 'Often injured together with rhomboid major in whiplash or upper back strain. Difficult to isolate clinically from rhomboid major.',
    originBones: ['c7', 't1'], insertionBones: ['scapula_r', 'scapula_l'],
  },
  {
    id: 'erector_spinae', name: 'Erector Spinae (Group)', latinName: 'Musculus erector spinae', category: 'back',
    origin: 'Common origin: posterior sacrum, iliac crest, sacroiliac ligaments, lumbar spinous processes',
    insertion: 'Iliocostalis: angles of ribs. Longissimus: transverse processes and ribs. Spinalis: spinous processes',
    function: 'Bilateral: extends vertebral column, holds upright posture. Unilateral: lateral flexion of spine',
    innervation: 'Dorsal rami of spinal nerves at corresponding segmental levels',
    bloodSupply: 'Posterior branches of intercostal, lumbar, and lateral sacral arteries',
    clinicalNotes: 'Major stabilizer of spine. Most common site of non-specific low back pain. Spasm causes "locked back." Hyperextension injuries damage these muscles. Targeted in back rehabilitation.',
    originBones: ['sacrum', 'ilium_r', 'ilium_l', 'l1', 'l2', 'l3', 'l4', 'l5'], insertionBones: ['t1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10', 't11', 't12', 'occipital'],
  },
  {
    id: 'quadratus_lumborum', name: 'Quadratus Lumborum', latinName: 'Musculus quadratus lumborum', category: 'back',
    origin: 'Posterior iliac crest and iliolumbar ligament',
    insertion: 'Transverse processes of L1–L4; lower border of 12th rib',
    function: 'Lateral flexion of lumbar spine; anchors 12th rib during forced expiration; assists lumbar extension',
    innervation: 'Ventral rami T12–L3',
    bloodSupply: 'Lumbar arteries, subcostal artery',
    clinicalNotes: 'Common cause of lateral hip/low back pain ("hip hiker" muscle). Spasm creates visible list (lateral lean) of trunk. Trigger points refer pain to buttocks and groin.',
    originBones: ['ilium_r', 'ilium_l', 'l1', 'l2', 'l3', 'l4'], insertionBones: ['rib_r12', 'rib_l12'],
  },
  {
    id: 'multifidus', name: 'Multifidus', latinName: 'Musculus multifidus', category: 'back',
    origin: 'Posterior sacrum, iliac spine, mammillary processes of lumbar vertebrae, transverse processes of T1–T12, articular processes of C4–C7',
    insertion: 'Spinous processes 2–4 segments above origin',
    function: 'Stabilizes vertebral column segment by segment; extends and rotates spine',
    innervation: 'Dorsal rami of spinal nerves',
    bloodSupply: 'Dorsal branches of posterior intercostal and lumbar arteries',
    clinicalNotes: 'Deepest of the back extensors and most critical for spinal stability. Atrophies rapidly after back injury or surgery — targeted specifically in spinal rehabilitation. MRI shows fatty infiltration in chronic low back pain.',
    originBones: ['sacrum', 'l1', 'l2', 'l3', 'l4', 'l5'], insertionBones: ['l1', 'l2', 'l3', 'l4', 'l5', 't1', 't2', 't3', 't4'],
  },
  // ─── CHEST MUSCLES ─────────────────────────────────────────────────────────
  {
    id: 'pectoralis_major', name: 'Pectoralis Major', latinName: 'Musculus pectoralis major', category: 'chest',
    origin: 'Clavicular head: medial half of clavicle. Sternocostal head: sternum and costal cartilages 1–6. Abdominal head: external oblique aponeurosis',
    insertion: 'Lateral lip of intertubercular groove of humerus',
    function: 'Adducts, flexes (clavicular head), and medially rotates humerus; draws arm across chest',
    innervation: 'Medial and lateral pectoral nerves (C5–T1)',
    bloodSupply: 'Thoracoacromial artery (pectoral branch), lateral thoracic artery',
    clinicalNotes: 'Rupture common in weightlifters (bench press). Absence (Poland syndrome) associated with ipsilateral limb anomalies. Pectoral nerve block for breast and shoulder surgery analgesia.',
    originBones: ['clavicle_r', 'clavicle_l', 'manubrium', 'sternum_body', 'rib_r1', 'rib_r2', 'rib_r3', 'rib_r4', 'rib_r5', 'rib_r6'], insertionBones: ['humerus_r', 'humerus_l'],
  },
  {
    id: 'pectoralis_minor', name: 'Pectoralis Minor', latinName: 'Musculus pectoralis minor', category: 'chest',
    origin: 'Outer surfaces of ribs 3–5 (near costal cartilages)',
    insertion: 'Coracoid process of scapula',
    function: 'Protracts (tips forward) and depresses scapula; elevates ribs during forced inspiration',
    innervation: 'Medial pectoral nerve (C8–T1)',
    bloodSupply: 'Thoracoacromial artery, lateral thoracic artery',
    clinicalNotes: 'Tightness tilts scapula anteriorly causing shoulder impingement. Pectoralis minor syndrome: neurovascular compression under coracoid. Pec minor stretching crucial in shoulder rehabilitation.',
    originBones: ['rib_r3', 'rib_r4', 'rib_r5', 'rib_l3', 'rib_l4', 'rib_l5'], insertionBones: ['scapula_r', 'scapula_l'],
  },
  {
    id: 'serratus_anterior', name: 'Serratus Anterior', latinName: 'Musculus serratus anterior', category: 'chest',
    origin: 'Lateral surfaces of ribs 1–8 (and 9) by digitations',
    insertion: 'Anterior (costal) surface of medial border of scapula',
    function: 'Protracts and rotates scapula superiorly (upward rotation); holds scapula against thorax',
    innervation: 'Long thoracic nerve (C5–C7)',
    bloodSupply: 'Lateral thoracic artery, thoracodorsal artery',
    clinicalNotes: 'Long thoracic nerve injury (mastectomy, axillary dissection, backpack palsy) causes medial winging of scapula — hallmark "angel wing" deformity. Essential for overhead activity.',
    originBones: ['rib_r1', 'rib_r2', 'rib_r3', 'rib_r4', 'rib_r5', 'rib_r6', 'rib_r7', 'rib_r8'], insertionBones: ['scapula_r', 'scapula_l'],
  },
  {
    id: 'diaphragm', name: 'Diaphragm', latinName: 'Diaphragma', category: 'chest',
    origin: 'Sternal part: xiphoid process. Costal part: inner surfaces of ribs 7–12. Lumbar part: L1–L3 vertebrae (crura)',
    insertion: 'Central tendon',
    function: 'Primary muscle of respiration; descends during inspiration to increase thoracic volume; increases intra-abdominal pressure (defecation, childbirth)',
    innervation: 'Phrenic nerve (C3–C5) — "C3,4,5 keeps the diaphragm alive"',
    bloodSupply: 'Phrenic arteries, musculophrenic arteries, pericardiacophrenic arteries',
    clinicalNotes: 'Phrenic nerve injury (C3–C5 level) or neck surgery → ipsilateral hemidiaphragm paralysis, elevated on CXR. Hiccups from diaphragm spasm. Hiatal hernia: stomach herniates through esophageal hiatus. Passes: aorta (T12), esophagus (T10), IVC (T8).',
    originBones: ['xiphoid', 'rib_r7', 'rib_r8', 'rib_r9', 'rib_r10', 'rib_r11', 'rib_r12', 'l1', 'l2', 'l3'], insertionBones: ['xiphoid'],
  },
  {
    id: 'intercostal_ext', name: 'External Intercostals', latinName: 'Musculi intercostales externi', category: 'chest',
    origin: 'Lower border of each rib',
    insertion: 'Upper border of the rib below (11 pairs)',
    function: 'Elevate ribs during inspiration; stabilize intercostal spaces',
    innervation: 'Intercostal nerves (T1–T11)',
    bloodSupply: 'Posterior intercostal arteries, anterior intercostal arteries',
    clinicalNotes: 'Thoracocentesis (pleural tap) placed above rib to avoid intercostal neurovascular bundle running below each rib. Intercostal nerve block targets these spaces for pain control.',
    originBones: ['rib_r1', 'rib_r2', 'rib_r3', 'rib_r4', 'rib_r5', 'rib_r6', 'rib_r7', 'rib_r8', 'rib_r9', 'rib_r10', 'rib_r11'],
    insertionBones: ['rib_r2', 'rib_r3', 'rib_r4', 'rib_r5', 'rib_r6', 'rib_r7', 'rib_r8', 'rib_r9', 'rib_r10', 'rib_r11', 'rib_r12'],
  },
  // ─── SHOULDER MUSCLES ──────────────────────────────────────────────────────
  {
    id: 'deltoid', name: 'Deltoid', latinName: 'Musculus deltoideus', category: 'shoulder',
    origin: 'Anterior: lateral third of clavicle. Middle: acromion. Posterior: spine of scapula',
    insertion: 'Deltoid tuberosity of humerus',
    function: 'Anterior: flexion and medial rotation of arm. Middle: abduction of arm. Posterior: extension and lateral rotation of arm',
    innervation: 'Axillary nerve (C5–C6)',
    bloodSupply: 'Posterior circumflex humeral artery, thoracoacromial artery (deltoid branch)',
    clinicalNotes: 'Axillary nerve injury (shoulder dislocation, humeral neck fracture) → deltoid paralysis (cannot abduct arm). Common IM injection site. Regimental badge area: lateral deltoid sensory territory of axillary nerve.',
    originBones: ['clavicle_r', 'clavicle_l', 'scapula_r', 'scapula_l'], insertionBones: ['humerus_r', 'humerus_l'],
  },
  {
    id: 'supraspinatus', name: 'Supraspinatus', latinName: 'Musculus supraspinatus', category: 'shoulder',
    origin: 'Supraspinous fossa of scapula',
    insertion: 'Superior facet of greater tubercle of humerus',
    function: 'Initiates abduction of arm (first 0–15°); stabilizes glenohumeral joint',
    innervation: 'Suprascapular nerve (C4–C6)',
    bloodSupply: 'Suprascapular artery, posterior circumflex humeral artery',
    clinicalNotes: 'Most commonly torn rotator cuff tendon (>90% of tears). Critical zone: ~1 cm from insertion, poorly vascularized ("watershed zone"). Supraspinatus test (empty can): arm at 90° abduction, 30° forward, thumb down. MRI gold standard for diagnosis.',
    originBones: ['scapula_r', 'scapula_l'], insertionBones: ['humerus_r', 'humerus_l'],
  },
  {
    id: 'infraspinatus', name: 'Infraspinatus', latinName: 'Musculus infraspinatus', category: 'shoulder',
    origin: 'Infraspinous fossa of scapula',
    insertion: 'Middle facet of greater tubercle of humerus',
    function: 'Lateral (external) rotation of humerus; stabilizes glenohumeral joint posteriorly',
    innervation: 'Suprascapular nerve (C5–C6)',
    bloodSupply: 'Suprascapular artery, circumflex scapular artery',
    clinicalNotes: 'Second most commonly torn rotator cuff muscle. Lag sign: inability to hold arm in external rotation indicates infraspinatus tear. Volleyball spike mechanism injures suprascapular nerve at spinoglenoid notch.',
    originBones: ['scapula_r', 'scapula_l'], insertionBones: ['humerus_r', 'humerus_l'],
  },
  {
    id: 'teres_minor', name: 'Teres Minor', latinName: 'Musculus teres minor', category: 'shoulder',
    origin: 'Superior portion of lateral border of scapula',
    insertion: 'Inferior facet of greater tubercle of humerus',
    function: 'Lateral (external) rotation of humerus; weakly adducts arm; stabilizes glenohumeral joint',
    innervation: 'Axillary nerve (C5–C6)',
    bloodSupply: 'Circumflex scapular artery, posterior circumflex humeral artery',
    clinicalNotes: 'Part of rotator cuff ("SITS": Supraspinatus, Infraspinatus, Teres minor, Subscapularis). Axillary nerve injury also denervates teres minor along with deltoid. Rarely torn in isolation.',
    originBones: ['scapula_r', 'scapula_l'], insertionBones: ['humerus_r', 'humerus_l'],
  },
  {
    id: 'subscapularis', name: 'Subscapularis', latinName: 'Musculus subscapularis', category: 'shoulder',
    origin: 'Subscapular fossa (anterior/costal surface of scapula)',
    insertion: 'Lesser tubercle of humerus and joint capsule',
    function: 'Medial (internal) rotation and adduction of humerus; stabilizes glenohumeral joint anteriorly',
    innervation: 'Upper and lower subscapular nerves (C5–C7)',
    bloodSupply: 'Subscapular artery, lateral thoracic artery',
    clinicalNotes: 'Only anterior rotator cuff muscle. Tear causes loss of internal rotation. Lift-off test and belly-press test assess subscapularis integrity. Important in anterior shoulder instability.',
    originBones: ['scapula_r', 'scapula_l'], insertionBones: ['humerus_r', 'humerus_l'],
  },
  {
    id: 'teres_major', name: 'Teres Major', latinName: 'Musculus teres major', category: 'shoulder',
    origin: 'Posterior surface of inferior angle of scapula',
    insertion: 'Medial lip of intertubercular groove of humerus',
    function: 'Adducts and medially rotates humerus; extends shoulder from flexed position',
    innervation: 'Lower subscapular nerve (C5–C7)',
    bloodSupply: 'Circumflex scapular artery',
    clinicalNotes: 'Called "little lats" — acts with latissimus dorsi. Not part of rotator cuff (does not attach to joint capsule). Axillary space between teres major and minor contains axillary nerve and posterior humeral circumflex artery.',
    originBones: ['scapula_r', 'scapula_l'], insertionBones: ['humerus_r', 'humerus_l'],
  },
  // ─── ARM MUSCLES ───────────────────────────────────────────────────────────
  {
    id: 'biceps_brachii', name: 'Biceps Brachii', latinName: 'Musculus biceps brachii', category: 'arm',
    origin: 'Long head: supraglenoid tubercle of scapula. Short head: coracoid process of scapula',
    insertion: 'Radial tuberosity; bicipital aponeurosis (into deep fascia of forearm)',
    function: 'Flexion of elbow (most powerful when forearm supinated); supination of forearm; assists shoulder flexion',
    innervation: 'Musculocutaneous nerve (C5–C6)',
    bloodSupply: 'Brachial artery, anterior circumflex humeral artery',
    clinicalNotes: 'Long head tendon rupture causes "Popeye sign" (muscle belly bunches distally). Distal biceps tendon rupture (at radial tuberosity) requires surgical repair. Biceps reflex tests C5–C6. "The muscle that turns the key and pours the wine."',
    originBones: ['scapula_r', 'scapula_l'], insertionBones: ['radius_r', 'radius_l'],
  },
  {
    id: 'brachialis', name: 'Brachialis', latinName: 'Musculus brachialis', category: 'arm',
    origin: 'Distal half of anterior humerus',
    insertion: 'Coronoid process and tuberosity of ulna',
    function: 'Pure elbow flexion (works regardless of forearm position); "workhorse" flexor',
    innervation: 'Musculocutaneous nerve (C5–C6) + small radial nerve branch (C7)',
    bloodSupply: 'Radial and ulnar recurrent arteries, brachial artery',
    clinicalNotes: 'Strongest elbow flexor. Always active in elbow flexion unlike biceps which is position-dependent. Myositis ossificans (bone within muscle) can follow elbow injury — avoid aggressive massage.',
    originBones: ['humerus_r', 'humerus_l'], insertionBones: ['ulna_r', 'ulna_l'],
  },
  {
    id: 'triceps_brachii', name: 'Triceps Brachii', latinName: 'Musculus triceps brachii', category: 'arm',
    origin: 'Long head: infraglenoid tubercle of scapula. Lateral head: posterior humerus (above radial groove). Medial head: posterior humerus (below radial groove)',
    insertion: 'Olecranon of ulna',
    function: 'Extension of elbow; long head extends and adducts shoulder',
    innervation: 'Radial nerve (C6–C8)',
    bloodSupply: 'Profunda brachii artery (deep brachial artery)',
    clinicalNotes: 'Triceps reflex tests C7. Radial nerve (in radial groove) injured with humeral shaft fractures → wrist drop. Long head passes through triangular interval (with radial nerve and profunda brachii). Triceps tendon rupture rare — only complete tendon rupture common in men over 30.',
    originBones: ['scapula_r', 'scapula_l', 'humerus_r', 'humerus_l'], insertionBones: ['ulna_r', 'ulna_l'],
  },
  {
    id: 'coracobrachialis', name: 'Coracobrachialis', latinName: 'Musculus coracobrachialis', category: 'arm',
    origin: 'Coracoid process of scapula',
    insertion: 'Middle third of medial surface of humerus',
    function: 'Flexion and adduction of arm at shoulder; stabilizes shoulder joint',
    innervation: 'Musculocutaneous nerve (C5–C7) — pierces this muscle',
    bloodSupply: 'Anterior circumflex humeral artery, brachial artery',
    clinicalNotes: 'Musculocutaneous nerve pierces coracobrachialis (unique among major nerves). Compression here causes lateral forearm numbness. Coracoid process palpable below clavicle — attachment of 3 structures: pec minor, short head biceps, coracobrachialis.',
    originBones: ['scapula_r', 'scapula_l'], insertionBones: ['humerus_r', 'humerus_l'],
  },
  // ─── FOREARM MUSCLES ───────────────────────────────────────────────────────
  {
    id: 'brachioradialis', name: 'Brachioradialis', latinName: 'Musculus brachioradialis', category: 'forearm',
    origin: 'Lateral supracondylar ridge of humerus',
    insertion: 'Styloid process of radius',
    function: 'Flexion of forearm at elbow (most efficient when forearm in neutral semi-prone position)',
    innervation: 'Radial nerve (C5–C6)',
    bloodSupply: 'Radial recurrent artery',
    clinicalNotes: 'Forms the lateral border of the cubital fossa. Tested in elbow flexion with forearm in neutral position. Radial nerve palsy spares brachioradialis (C5–C6) while causing wrist drop (C7–C8 muscles). Palpable landmark for radial pulse.',
    originBones: ['humerus_r', 'humerus_l'], insertionBones: ['radius_r', 'radius_l'],
  },
  {
    id: 'pronator_teres', name: 'Pronator Teres', latinName: 'Musculus pronator teres', category: 'forearm',
    origin: 'Humeral head: medial epicondyle. Ulnar head: coronoid process of ulna',
    insertion: 'Middle of lateral surface of radius',
    function: 'Pronation of forearm; assists elbow flexion',
    innervation: 'Median nerve (C6–C7)',
    bloodSupply: 'Ulnar artery, radial artery',
    clinicalNotes: 'Pronator teres syndrome: median nerve compressed between two heads causing forearm pain and hand numbness (differs from carpal tunnel: no nocturnal symptoms, worse with resisted pronation). Superficial and easily palpable.',
    originBones: ['humerus_r', 'humerus_l', 'ulna_r', 'ulna_l'], insertionBones: ['radius_r', 'radius_l'],
  },
  {
    id: 'flexor_carpi_radialis', name: 'Flexor Carpi Radialis', latinName: 'Musculus flexor carpi radialis', category: 'forearm',
    origin: 'Medial epicondyle of humerus (common flexor origin)',
    insertion: 'Base of 2nd and 3rd metacarpals',
    function: 'Flexion and radial deviation (abduction) of wrist',
    innervation: 'Median nerve (C6–C7)',
    bloodSupply: 'Radial artery',
    clinicalNotes: 'Tendon palpable at wrist — radial pulse landmark. FCR tendinopathy causes radial-sided wrist pain. Tendon used as landmark for carpal tunnel injection. Landmark for radial artery cannulation.',
    originBones: ['humerus_r', 'humerus_l'], insertionBones: ['mc_r2', 'mc_r3', 'mc_l2', 'mc_l3'],
  },
  {
    id: 'flexor_carpi_ulnaris', name: 'Flexor Carpi Ulnaris', latinName: 'Musculus flexor carpi ulnaris', category: 'forearm',
    origin: 'Humeral head: medial epicondyle. Ulnar head: olecranon and posterior ulna',
    insertion: 'Pisiform (then via ligaments to hamate hook and 5th metacarpal)',
    function: 'Flexion and ulnar deviation (adduction) of wrist',
    innervation: 'Ulnar nerve (C7–T1)',
    bloodSupply: 'Ulnar artery',
    clinicalNotes: 'Ulnar nerve runs along medial border of FCU in the forearm. FCU tendinopathy presents as medial wrist pain. Pisiform bone is a sesamoid within FCU tendon. Guyon canal: ulnar nerve compressed here → ulnar hand numbness.',
    originBones: ['humerus_r', 'humerus_l', 'ulna_r', 'ulna_l'], insertionBones: ['pisiform_r', 'pisiform_l'],
  },
  {
    id: 'extensor_carpi_radialis_longus', name: 'Extensor Carpi Radialis Longus', latinName: 'Musculus extensor carpi radialis longus', category: 'forearm',
    origin: 'Lateral supracondylar ridge of humerus',
    insertion: 'Base of 2nd metacarpal (dorsal surface)',
    function: 'Extension and radial deviation of wrist; assists elbow flexion',
    innervation: 'Radial nerve (C6–C7)',
    bloodSupply: 'Radial recurrent artery, radial artery',
    clinicalNotes: 'One of main wrist extensors (wrist drop from radial nerve lesion). ECRL and ECRB overuse → lateral epicondylitis ("tennis elbow"). These tendons form the radial border of anatomical snuffbox.',
    originBones: ['humerus_r', 'humerus_l'], insertionBones: ['mc_r2', 'mc_l2'],
  },
  {
    id: 'extensor_digitorum', name: 'Extensor Digitorum', latinName: 'Musculus extensor digitorum', category: 'forearm',
    origin: 'Lateral epicondyle of humerus (common extensor origin)',
    insertion: 'Extensor expansion of fingers 2–5 (dorsal digital expansion)',
    function: 'Extends fingers 2–5 at MCP and IP joints; assists wrist extension',
    innervation: 'Posterior interosseous nerve (deep branch of radial nerve, C7–C8)',
    bloodSupply: 'Posterior interosseous artery',
    clinicalNotes: 'Common extensor origin — lateral epicondyle — site of tennis elbow (lateral epicondylitis). Radial nerve palsy prevents finger/wrist extension. Extensor tendon lacerations at dorsal hand need surgical repair.',
    originBones: ['humerus_r', 'humerus_l'], insertionBones: ['pp_r2', 'pp_r3', 'pp_r4', 'pp_r5'],
  },
  {
    id: 'supinator', name: 'Supinator', latinName: 'Musculus supinator', category: 'forearm',
    origin: 'Lateral epicondyle, radial collateral ligament, annular ligament, supinator crest of ulna',
    insertion: 'Lateral surface of proximal radius (wraps around)',
    function: 'Supination of forearm (with elbow extended or flexed)',
    innervation: 'Deep branch of radial nerve (posterior interosseous nerve, C5–C6)',
    bloodSupply: 'Radial recurrent artery, posterior interosseous artery',
    clinicalNotes: 'Posterior interosseous nerve passes through the radial tunnel between two heads of supinator — compression causes lateral elbow pain (radial tunnel syndrome) and finger drop (PIN palsy). Radial head fracture may injure PIN in this region.',
    originBones: ['humerus_r', 'humerus_l', 'ulna_r', 'ulna_l'], insertionBones: ['radius_r', 'radius_l'],
  },
  {
    id: 'pronator_quadratus', name: 'Pronator Quadratus', latinName: 'Musculus pronator quadratus', category: 'forearm',
    origin: 'Distal quarter of anterior ulna',
    insertion: 'Distal quarter of anterior radius',
    function: 'Primary pronation of forearm; binds radius to ulna distally',
    innervation: 'Anterior interosseous nerve (branch of median nerve, C7–C8)',
    bloodSupply: 'Anterior interosseous artery',
    clinicalNotes: 'Deep to other forearm flexors, difficult to examine. Anterior interosseous nerve syndrome: weakness of pronator quadratus, FPL, and FDP to index — no sensory loss. Deep to distal forearm — involved in distal radius fractures.',
    originBones: ['ulna_r', 'ulna_l'], insertionBones: ['radius_r', 'radius_l'],
  },
  // ─── HAND MUSCLES ──────────────────────────────────────────────────────────
  {
    id: 'abductor_pollicis_brevis', name: 'Abductor Pollicis Brevis', latinName: 'Musculus abductor pollicis brevis', category: 'hand',
    origin: 'Flexor retinaculum and tubercles of scaphoid and trapezium',
    insertion: 'Radial side of base of proximal phalanx of thumb',
    function: 'Abducts thumb; assists in opposition',
    innervation: 'Recurrent branch of median nerve (C8–T1)',
    bloodSupply: 'Superficial palmar arch',
    clinicalNotes: 'First muscle to waste in carpal tunnel syndrome — thenar eminence flattening. Simian hand deformity. Recurrent (motor) branch of median nerve damaged during carpal tunnel surgery if anatomy variant. Opposition test: can patient touch thumb to little finger?',
    originBones: ['scaphoid_r', 'trapezium_r', 'scaphoid_l', 'trapezium_l'], insertionBones: ['pp_r1', 'pp_l1'],
  },
  {
    id: 'adductor_pollicis', name: 'Adductor Pollicis', latinName: 'Musculus adductor pollicis', category: 'hand',
    origin: 'Oblique head: capitate and bases of 2nd–3rd metacarpals. Transverse head: shaft of 3rd metacarpal',
    insertion: 'Medial side of base of proximal phalanx of thumb',
    function: 'Adducts thumb toward palm; assists in gripping',
    innervation: 'Deep branch of ulnar nerve (C8–T1)',
    bloodSupply: 'Deep palmar arch (princeps pollicis artery)',
    clinicalNotes: 'Froment\'s sign: unable to hold paper between thumb and index without flexing thumb IP joint (compensates for adductor pollicis weakness) — tests ulnar nerve. Wasted adductor pollicis seen in ulnar nerve palsy.',
    originBones: ['capitate_r', 'mc_r2', 'mc_r3', 'capitate_l', 'mc_l2', 'mc_l3'], insertionBones: ['pp_r1', 'pp_l1'],
  },
  {
    id: 'lumbricals', name: 'Lumbricals', latinName: 'Musculi lumbricales manus', category: 'hand',
    origin: 'Tendons of flexor digitorum profundus',
    insertion: 'Lateral (radial) side of extensor expansion of fingers 2–5',
    function: 'Flex MCP joints while extending PIP and DIP joints ("intrinsic plus" position)',
    innervation: '1st and 2nd: median nerve. 3rd and 4th: deep branch of ulnar nerve (C8–T1)',
    bloodSupply: 'Digital arteries from superficial palmar arch',
    clinicalNotes: 'Unique: both origin and insertion are tendons (not bone). Lumbrical plus deformity: paradoxical MCP extension when FDP tendon cut proximally. Critical for fine motor tasks. "Intrinsic-plus" position (MP flexed, IP extended) for safe splinting after hand injury.',
    originBones: [], insertionBones: ['pp_r2', 'pp_r3', 'pp_r4', 'pp_r5'],
  },
  {
    id: 'interossei_dorsal', name: 'Dorsal Interossei', latinName: 'Musculi interossei dorsales manus', category: 'hand',
    origin: 'Adjacent sides of metacarpal bones (bipennate, 4 muscles)',
    insertion: 'Bases of proximal phalanges and extensor expansion of fingers 2–4',
    function: 'ABduct fingers from middle finger axis; flex MCP joints; extend IP joints',
    innervation: 'Deep branch of ulnar nerve (C8–T1)',
    bloodSupply: 'Dorsal metacarpal arteries, deep palmar arch',
    clinicalNotes: 'First dorsal interosseous wasting — visible groove between thumb and index finger in ulnar nerve palsy. DAB = Dorsal ABduct. Tested by having patient spread fingers against resistance.',
    originBones: ['mc_r1', 'mc_r2', 'mc_r3', 'mc_r4', 'mc_r5'], insertionBones: ['pp_r2', 'pp_r3', 'pp_r4'],
  },
  // ─── ABDOMINAL MUSCLES ────────────────────────────────────────────────────
  {
    id: 'rectus_abdominis', name: 'Rectus Abdominis', latinName: 'Musculus rectus abdominis', category: 'abdominal',
    origin: 'Pubic symphysis and pubic crest',
    insertion: 'Xiphoid process and costal cartilages of ribs 5–7',
    function: 'Flexes lumbar vertebral column (crunches trunk); compresses abdominal viscera; assists in forced expiration',
    innervation: 'Anterior rami of T7–T12 (intercostal nerves)',
    bloodSupply: 'Superior and inferior epigastric arteries',
    clinicalNotes: 'Separated by linea alba — diastasis recti (separation) common in pregnancy. Rectus sheath — important landmark: arcuate line below which posterior sheath is absent. Epigastric vessels in sheath — hernias and laparoscopy complications. Six-pack visible when body fat <10%.',
    originBones: ['pubis_r', 'pubis_l'], insertionBones: ['xiphoid', 'rib_r5', 'rib_r6', 'rib_r7'],
  },
  {
    id: 'external_oblique', name: 'External Oblique', latinName: 'Musculus obliquus externus abdominis', category: 'abdominal',
    origin: 'External surfaces of ribs 5–12 (by digitations)',
    insertion: 'Iliac crest, pubic tubercle, linea alba (via aponeurosis); inguinal ligament',
    function: 'Flexes and rotates trunk (to opposite side); compresses abdomen; depresses ribs',
    innervation: 'Anterior rami of T8–T12, iliohypogastric and ilioinguinal nerves (L1)',
    bloodSupply: 'Lower intercostal arteries, deep circumflex iliac artery',
    clinicalNotes: 'Inguinal ligament = lower free edge of external oblique aponeurosis. Inguinal hernias related to external oblique aponeurosis. "Pocket hand" — fibers run inferomedially (hands-in-pockets direction).',
    originBones: ['rib_r5', 'rib_r6', 'rib_r7', 'rib_r8', 'rib_r9', 'rib_r10', 'rib_r11', 'rib_r12'], insertionBones: ['ilium_r', 'ilium_l', 'pubis_r', 'pubis_l'],
  },
  {
    id: 'internal_oblique', name: 'Internal Oblique', latinName: 'Musculus obliquus internus abdominis', category: 'abdominal',
    origin: 'Thoracolumbar fascia, anterior two-thirds of iliac crest, lateral inguinal ligament',
    insertion: 'Inferior borders of ribs 10–12, linea alba, pubic crest (via conjoint tendon)',
    function: 'Flexes and rotates trunk to same side; compresses abdomen; depresses ribs',
    innervation: 'Anterior rami of T8–L1',
    bloodSupply: 'Lower intercostal arteries, deep circumflex iliac artery, inferior epigastric artery',
    clinicalNotes: 'Fibers run perpendicular to external oblique (superomedially). Cremaster muscle in males derived from internal oblique — cremasteric reflex (L1). Conjoint tendon (ilio-inguinal nerve) reinforces posterior wall of inguinal canal.',
    originBones: ['ilium_r', 'ilium_l'], insertionBones: ['rib_r10', 'rib_r11', 'rib_r12', 'pubis_r', 'pubis_l'],
  },
  {
    id: 'transversus_abdominis', name: 'Transversus Abdominis', latinName: 'Musculus transversus abdominis', category: 'abdominal',
    origin: 'Inner surface of costal cartilages 7–12, thoracolumbar fascia, iliac crest, lateral inguinal ligament',
    insertion: 'Linea alba, pubic crest, pectineal line (via conjoint tendon)',
    function: 'Compresses and supports abdominal viscera; expiration; stabilizes lumbar spine (deep core)',
    innervation: 'Anterior rami T7–L1',
    bloodSupply: 'Lower intercostal arteries, inferior epigastric artery, deep circumflex iliac artery',
    clinicalNotes: 'Deepest abdominal muscle. Critical for lumbar spine stability — core strengthening targets transversus abdominis. TAP block (transversus abdominis plane block) for lower abdominal pain control. Transversalis fascia lies deep to it.',
    originBones: ['rib_r7', 'rib_r8', 'rib_r9', 'rib_r10', 'rib_r11', 'rib_r12', 'ilium_r', 'ilium_l'], insertionBones: ['pubis_r', 'pubis_l', 'xiphoid'],
  },
  {
    id: 'psoas_major', name: 'Psoas Major', latinName: 'Musculus psoas major', category: 'abdominal',
    origin: 'Transverse processes of T12–L5; vertebral bodies and intervertebral discs T12–L5',
    insertion: 'Lesser trochanter of femur (with iliacus = iliopsoas)',
    function: 'Flexion of hip; lateral flexion of lumbar spine when hip fixed',
    innervation: 'Anterior rami of L1–L3 (direct branches)',
    bloodSupply: 'Lumbar arteries, iliolumbar artery',
    clinicalNotes: 'Psoas abscess: collection within psoas sheath — TB classic cause; presents as hip flexion contracture and groin swelling. Psoas sign: passive hip extension causes pain (appendicitis, psoas abscess). Major hip flexor for walking, running stairs.',
    originBones: ['t12', 'l1', 'l2', 'l3', 'l4', 'l5'], insertionBones: ['femur_r', 'femur_l'],
  },
  // ─── HIP MUSCLES ───────────────────────────────────────────────────────────
  {
    id: 'gluteus_maximus', name: 'Gluteus Maximus', latinName: 'Musculus gluteus maximus', category: 'hip',
    origin: 'Posterior ilium (behind posterior gluteal line), posterior sacrum and coccyx, sacrotuberous ligament',
    insertion: '75% → iliotibial tract; 25% → gluteal tuberosity of femur',
    function: 'Powerful hip extension and lateral rotation; stabilizes knee via ITB; trunk extension over fixed thigh (e.g., rising from chair)',
    innervation: 'Inferior gluteal nerve (L5–S2)',
    bloodSupply: 'Superior and inferior gluteal arteries',
    clinicalNotes: 'Trendelenburg gait if weak (inferior gluteal nerve damage). Largest muscle in body. IM injection upper outer quadrant of buttock — avoids sciatic nerve. Superior gluteal nerve (L4–S1) lies above piriformis; inferior below. Gluteal compartment syndrome possible.',
    originBones: ['ilium_r', 'ilium_l', 'sacrum', 'coccyx'], insertionBones: ['femur_r', 'femur_l'],
  },
  {
    id: 'gluteus_medius', name: 'Gluteus Medius', latinName: 'Musculus gluteus medius', category: 'hip',
    origin: 'Outer surface of ilium between posterior and anterior gluteal lines',
    insertion: 'Lateral surface of greater trochanter of femur',
    function: 'Abducts hip; anterior fibers medially rotate; stabilizes pelvis in single-leg stance',
    innervation: 'Superior gluteal nerve (L4–S1)',
    bloodSupply: 'Superior gluteal artery',
    clinicalNotes: 'Trendelenburg sign: pelvis drops to contralateral side during single-leg stance — indicates weak gluteus medius. Gluteus medius tear (degenerative) causes lateral hip pain ("pseudo-trochanteric bursitis"). Key muscle in gait stabilization.',
    originBones: ['ilium_r', 'ilium_l'], insertionBones: ['femur_r', 'femur_l'],
  },
  {
    id: 'gluteus_minimus', name: 'Gluteus Minimus', latinName: 'Musculus gluteus minimus', category: 'hip',
    origin: 'Outer surface of ilium between anterior and inferior gluteal lines',
    insertion: 'Anterior surface of greater trochanter of femur',
    function: 'Abducts and medially rotates hip; stabilizes pelvis',
    innervation: 'Superior gluteal nerve (L4–S1)',
    bloodSupply: 'Superior gluteal artery',
    clinicalNotes: 'Deep to gluteus medius. Tears of gluteus minimus and medius together called "rotator cuff of hip." Lateral hip pain on MRI: distinguish from trochanteric bursitis.',
    originBones: ['ilium_r', 'ilium_l'], insertionBones: ['femur_r', 'femur_l'],
  },
  {
    id: 'piriformis', name: 'Piriformis', latinName: 'Musculus piriformis', category: 'hip',
    origin: 'Anterior surface of sacrum (S2–S4), sacrotuberous ligament',
    insertion: 'Superior border of greater trochanter of femur',
    function: 'Lateral rotation of hip (when extended); abduction of hip (when flexed >90°)',
    innervation: 'Nerve to piriformis (S1–S2)',
    bloodSupply: 'Superior and inferior gluteal arteries',
    clinicalNotes: 'Key landmark in buttock — most neurovascular structures emerge above or below piriformis. Piriformis syndrome: sciatic nerve compressed by piriformis causing buttock pain radiating down leg (mimics disc herniation). Sciatic nerve variation: 15% pass through piriformis.',
    originBones: ['sacrum'], insertionBones: ['femur_r', 'femur_l'],
  },
  {
    id: 'tensor_fasciae_latae', name: 'Tensor Fasciae Latae', latinName: 'Musculus tensor fasciae latae', category: 'hip',
    origin: 'Anterior superior iliac spine and adjacent iliac crest',
    insertion: 'Iliotibial band (tract) — inserts on lateral tibial condyle (Gerdy\'s tubercle)',
    function: 'Abducts, flexes and medially rotates hip; tenses IT band; stabilizes knee',
    innervation: 'Superior gluteal nerve (L4–L5)',
    bloodSupply: 'Superior gluteal artery, lateral circumflex femoral artery',
    clinicalNotes: 'IT band tightness → iliotibial band syndrome (lateral knee pain in runners). Ober\'s test: assesses IT band/TFL tightness. Snapping hip (coxa saltans) from IT band snapping over greater trochanter.',
    originBones: ['ilium_r', 'ilium_l'], insertionBones: ['tibia_r', 'tibia_l'],
  },
  {
    id: 'iliopsoas', name: 'Iliopsoas', latinName: 'Musculus iliopsoas', category: 'hip',
    origin: 'Iliacus: iliac fossa and sacral ala. Psoas major: T12–L5 vertebral bodies and transverse processes',
    insertion: 'Lesser trochanter of femur',
    function: 'Most powerful hip flexor; assists in lumbar flexion',
    innervation: 'Iliacus: femoral nerve (L2–L4). Psoas: direct lumbar branches L1–L3',
    bloodSupply: 'Iliolumbar artery, medial circumflex femoral artery',
    clinicalNotes: 'Primary hip flexor — critical for walking and stair climbing. Iliopsoas tendinopathy causes anterior hip pain. Iliopectineal bursitis. Hip impingement: snapping of iliopsoas tendon (coxa saltans interna). Tight hip flexors contribute to anterior pelvic tilt and low back pain.',
    originBones: ['ilium_r', 'ilium_l', 'l1', 'l2', 'l3', 'l4', 'l5'], insertionBones: ['femur_r', 'femur_l'],
  },
  // ─── THIGH MUSCLES ────────────────────────────────────────────────────────
  {
    id: 'rectus_femoris', name: 'Rectus Femoris', latinName: 'Musculus rectus femoris', category: 'thigh',
    origin: 'Anterior inferior iliac spine (AIIS); iliac portion of acetabular rim',
    insertion: 'Quadriceps tendon → patella → patellar ligament → tibial tuberosity',
    function: 'Extends knee; flexes hip (two-joint muscle)',
    innervation: 'Femoral nerve (L2–L4)',
    bloodSupply: 'Lateral circumflex femoral artery',
    clinicalNotes: 'Only two-joint muscle in quadriceps group — crosses both hip and knee. Avulsion fractures at AIIS common in adolescents (kicking sports). Rectus femoris strain = "charley horse." Visible as central thigh muscle on anterior view.',
    originBones: ['ilium_r', 'ilium_l'], insertionBones: ['patella_r', 'patella_l', 'tibia_r', 'tibia_l'],
  },
  {
    id: 'vastus_lateralis', name: 'Vastus Lateralis', latinName: 'Musculus vastus lateralis', category: 'thigh',
    origin: 'Greater trochanter and lateral lip of linea aspera of femur',
    insertion: 'Lateral border of patella; quadriceps tendon; tibial tuberosity (via patellar ligament)',
    function: 'Extends knee',
    innervation: 'Femoral nerve (L2–L4)',
    bloodSupply: 'Lateral circumflex femoral artery',
    clinicalNotes: 'Largest quadriceps component. Common IM injection site in infants and elderly. Patellar tracking problems: dominance of vastus lateralis vs. VMO (vastus medialis oblique) leads to lateral patellar tilt.',
    originBones: ['femur_r', 'femur_l'], insertionBones: ['patella_r', 'patella_l'],
  },
  {
    id: 'vastus_medialis', name: 'Vastus Medialis', latinName: 'Musculus vastus medialis', category: 'thigh',
    origin: 'Medial lip of linea aspera, medial supracondylar ridge of femur; intertrochanteric line',
    insertion: 'Medial border of patella; quadriceps tendon; tibial tuberosity',
    function: 'Extends knee; VMO (oblique fibers) stabilizes patella medially in final 30° of extension',
    innervation: 'Femoral nerve (L2–L4)',
    bloodSupply: 'Femoral artery, descending genicular artery',
    clinicalNotes: 'VMO (Vastus Medialis Oblique) wasting prominent early in knee pathology. Patellofemoral syndrome: VMO/VL imbalance. Saphenous nerve at hunter\'s canal (adductor canal) adjacent to vastus medialis.',
    originBones: ['femur_r', 'femur_l'], insertionBones: ['patella_r', 'patella_l'],
  },
  {
    id: 'biceps_femoris', name: 'Biceps Femoris', latinName: 'Musculus biceps femoris', category: 'thigh',
    origin: 'Long head: ischial tuberosity. Short head: lateral lip of linea aspera, lateral supracondylar ridge of femur',
    insertion: 'Head of fibula; lateral condyle of tibia',
    function: 'Extends hip (long head); flexes knee; laterally rotates flexed knee',
    innervation: 'Long head: tibial portion of sciatic nerve (L5–S2). Short head: peroneal portion of sciatic nerve (L5–S2)',
    bloodSupply: 'Perforating branches of profunda femoris, popliteal artery branches',
    clinicalNotes: 'Hamstring strains most common in sprinters (proximal muscle belly or ischial origin avulsion). Common peroneal nerve winds around fibular neck just distal to biceps femoris insertion → nerve vulnerable to injury here. Long head only hamstring with dual sciatic supply.',
    originBones: ['ischium_r', 'ischium_l', 'femur_r', 'femur_l'], insertionBones: ['fibula_r', 'fibula_l', 'tibia_r', 'tibia_l'],
  },
  {
    id: 'semitendinosus', name: 'Semitendinosus', latinName: 'Musculus semitendinosus', category: 'thigh',
    origin: 'Ischial tuberosity (with long head of biceps femoris)',
    insertion: 'Proximal medial tibia (pes anserinus — with gracilis and sartorius)',
    function: 'Extends hip; flexes knee; medially rotates flexed knee',
    innervation: 'Tibial portion of sciatic nerve (L5–S2)',
    bloodSupply: 'Perforating branches of profunda femoris',
    clinicalNotes: 'Long tendon visible/palpable medially in popliteal fossa. Harvested with gracilis for ACL reconstruction (semitendinosus-gracilis graft). Pes anserinus bursitis: medial knee pain in overweight women with OA.',
    originBones: ['ischium_r', 'ischium_l'], insertionBones: ['tibia_r', 'tibia_l'],
  },
  {
    id: 'semimembranosus', name: 'Semimembranosus', latinName: 'Musculus semimembranosus', category: 'thigh',
    origin: 'Ischial tuberosity',
    insertion: 'Posterior medial condyle of tibia; oblique popliteal ligament; popliteus fascia',
    function: 'Extends hip; flexes knee; medially rotates flexed knee; reinforces posterior knee capsule',
    innervation: 'Tibial portion of sciatic nerve (L5–S2)',
    bloodSupply: 'Perforating branches of profunda femoris',
    clinicalNotes: 'Broad membranous proximal tendon (hence "membrano-"). Baker\'s cyst: fluid from knee joint communicates with semimembranosus bursa — presents as posterior knee swelling. Lateral to semitendinosus tendon in popliteal fossa.',
    originBones: ['ischium_r', 'ischium_l'], insertionBones: ['tibia_r', 'tibia_l'],
  },
  {
    id: 'adductor_longus', name: 'Adductor Longus', latinName: 'Musculus adductor longus', category: 'thigh',
    origin: 'Body of pubis (below pubic crest)',
    insertion: 'Middle third of linea aspera of femur',
    function: 'Adducts and medially rotates hip; flexes thigh',
    innervation: 'Anterior division of obturator nerve (L2–L4)',
    bloodSupply: 'Profunda femoris artery, medial circumflex femoral artery',
    clinicalNotes: 'Most commonly strained groin muscle ("groin pull"). Adductor longus tendon palpable at groin — landmark for femoral triangle. Sports hernia involves adductor longus and external oblique aponeurosis.',
    originBones: ['pubis_r', 'pubis_l'], insertionBones: ['femur_r', 'femur_l'],
  },
  {
    id: 'gracilis', name: 'Gracilis', latinName: 'Musculus gracilis', category: 'thigh',
    origin: 'Body and inferior ramus of pubis',
    insertion: 'Proximal medial tibia (pes anserinus)',
    function: 'Adducts hip; flexes and medially rotates knee',
    innervation: 'Anterior division of obturator nerve (L2–L3)',
    bloodSupply: 'Medial circumflex femoral artery, obturator artery',
    clinicalNotes: 'Long slender muscle — commonly harvested for free muscle transfers (facial reanimation, sphincter repair) and ACL reconstruction (with semitendinosus). Gracilis flap for perineal reconstruction.',
    originBones: ['pubis_r', 'pubis_l', 'ischium_r', 'ischium_l'], insertionBones: ['tibia_r', 'tibia_l'],
  },
  {
    id: 'sartorius', name: 'Sartorius', latinName: 'Musculus sartorius', category: 'thigh',
    origin: 'Anterior superior iliac spine (ASIS)',
    insertion: 'Proximal medial tibia (pes anserinus — superior surface)',
    function: 'Flexes, abducts and laterally rotates hip; flexes and medially rotates knee; "tailor\'s muscle"',
    innervation: 'Femoral nerve (L2–L3)',
    bloodSupply: 'Femoral artery, lateral circumflex femoral artery',
    clinicalNotes: 'Longest muscle in the body. Forms lateral border of femoral triangle (medial border: adductor longus; superior: inguinal ligament). Pes anserinus (sartorius + gracilis + semitendinosus) bursitis. "Tailor\'s muscle" — cross-legged sitting position.',
    originBones: ['ilium_r', 'ilium_l'], insertionBones: ['tibia_r', 'tibia_l'],
  },
  // ─── LEG MUSCLES ───────────────────────────────────────────────────────────
  {
    id: 'gastrocnemius', name: 'Gastrocnemius', latinName: 'Musculus gastrocnemius', category: 'leg',
    origin: 'Medial head: medial condyle of femur and posterior capsule. Lateral head: lateral condyle of femur',
    insertion: 'Calcaneus via calcaneal (Achilles) tendon (with soleus)',
    function: 'Plantarflexion of ankle; flexion of knee (crosses both joints)',
    innervation: 'Tibial nerve (S1–S2)',
    bloodSupply: 'Sural arteries (from popliteal artery)',
    clinicalNotes: 'Achilles tendon (gastrocnemius + soleus) — thickest tendon in body. Achilles tendon rupture: pop, weak plantarflexion, positive Thompson test (squeeze calf, no foot movement). Common in 40s "weekend warriors." Ankle reflex tests S1. Sural nerve runs between heads — harvested for nerve grafts.',
    originBones: ['femur_r', 'femur_l'], insertionBones: ['calcaneus_r', 'calcaneus_l'],
  },
  {
    id: 'soleus', name: 'Soleus', latinName: 'Musculus soleus', category: 'leg',
    origin: 'Posterior head of fibula, soleal line of tibia, fibrous arch between tibia and fibula',
    insertion: 'Calcaneus via calcaneal (Achilles) tendon',
    function: 'Plantarflexion of ankle; postural muscle preventing forward sway (standing)',
    innervation: 'Tibial nerve (S1–S2)',
    bloodSupply: 'Posterior tibial artery, peroneal artery',
    clinicalNotes: 'Deeper than gastrocnemius. Mainly slow-twitch (fatigue-resistant) — critical for standing. Soleus "venous pump" — contraction propels deep venous blood proximally. DVT frequently originates in soleal sinusoids. Thompson test assesses combined calf (gastrocnemius + soleus).',
    originBones: ['fibula_r', 'fibula_l', 'tibia_r', 'tibia_l'], insertionBones: ['calcaneus_r', 'calcaneus_l'],
  },
  {
    id: 'tibialis_anterior', name: 'Tibialis Anterior', latinName: 'Musculus tibialis anterior', category: 'leg',
    origin: 'Lateral condyle and proximal two-thirds of lateral tibia; interosseous membrane',
    insertion: 'Medial cuneiform and base of 1st metatarsal',
    function: 'Dorsiflexion of ankle; inversion of foot; supports medial longitudinal arch',
    innervation: 'Deep peroneal (fibular) nerve (L4–L5)',
    bloodSupply: 'Anterior tibial artery',
    clinicalNotes: 'Foot drop (inability to dorsiflex) from common peroneal nerve palsy at fibular neck. Anterior compartment syndrome after tibial fracture — emergency fasciotomy required. Largest muscle in anterior compartment. Tendon palpable at ankle dorsum.',
    originBones: ['tibia_r', 'tibia_l', 'fibula_r', 'fibula_l'], insertionBones: ['cuneiform1_r', 'cuneiform1_l', 'mt_r1', 'mt_l1'],
  },
  {
    id: 'extensor_digitorum_longus', name: 'Extensor Digitorum Longus', latinName: 'Musculus extensor digitorum longus', category: 'leg',
    origin: 'Lateral condyle of tibia, anterior head of fibula, interosseous membrane',
    insertion: 'Extensor expansion of toes 2–5',
    function: 'Extends toes 2–5; dorsiflexes ankle; everts foot',
    innervation: 'Deep peroneal nerve (L5–S1)',
    bloodSupply: 'Anterior tibial artery',
    clinicalNotes: 'Foot drop: loss of EDL and tibialis anterior → foot slap gait. Compartment syndrome in anterior compartment. Toe extension weakness from L5 radiculopathy.',
    originBones: ['tibia_r', 'tibia_l', 'fibula_r', 'fibula_l'], insertionBones: ['toe_pp_r2', 'toe_pp_r3', 'toe_pp_r4', 'toe_pp_r5'],
  },
  {
    id: 'fibularis_longus', name: 'Fibularis (Peroneus) Longus', latinName: 'Musculus fibularis longus', category: 'leg',
    origin: 'Head and proximal two-thirds of lateral fibula',
    insertion: 'Lateral cuneiform and base of 1st metatarsal (via long oblique course under foot)',
    function: 'Plantarflexion and eversion of foot; supports transverse and lateral arches',
    innervation: 'Superficial peroneal nerve (L5–S1)',
    bloodSupply: 'Peroneal artery',
    clinicalNotes: 'Inversion ankle sprains stretch/tear common peroneal and superficial peroneal nerves. Ankle sprain may avulse fibularis brevis at styloid process of 5th metatarsal. Long tendon crosses under foot in groove on cuboid — "stirrup" for arch support.',
    originBones: ['fibula_r', 'fibula_l'], insertionBones: ['cuneiform1_r', 'cuneiform1_l', 'mt_r1', 'mt_l1'],
  },
  {
    id: 'tibialis_posterior', name: 'Tibialis Posterior', latinName: 'Musculus tibialis posterior', category: 'leg',
    origin: 'Posterior surface of interosseous membrane, adjacent tibia and fibula',
    insertion: 'Navicular tuberosity; cuneiform bones; cuboid; bases of metatarsals 2–4',
    function: 'Plantarflexion and inversion of foot; supports medial longitudinal arch',
    innervation: 'Tibial nerve (L4–L5)',
    bloodSupply: 'Posterior tibial artery, peroneal artery',
    clinicalNotes: 'Tibialis posterior tendon dysfunction (PTTD) — most common cause of adult-acquired flatfoot. Progressive stages: tendinopathy → rupture → flatfoot deformity → arthritis. "Too many toes" sign. L4 weakness affects tibialis posterior and anterior.',
    originBones: ['tibia_r', 'tibia_l', 'fibula_r', 'fibula_l'], insertionBones: ['navicular_r', 'navicular_l', 'cuneiform1_r', 'cuneiform1_l'],
  },
  {
    id: 'flexor_hallucis_longus', name: 'Flexor Hallucis Longus', latinName: 'Musculus flexor hallucis longus', category: 'leg',
    origin: 'Posterior surface of fibula (distal two-thirds)',
    insertion: 'Base of distal phalanx of hallux (great toe)',
    function: 'Flexes great toe at all joints; plantarflexes and inverts foot; supports medial arch',
    innervation: 'Tibial nerve (L5–S2)',
    bloodSupply: 'Peroneal artery, posterior tibial artery',
    clinicalNotes: 'Most powerful toe flexor — critical for push-off in walking. FHL tenosynovitis in ballet dancers (forced plantarflexion). Tendon passes in groove on posterior talus — os trigonum may cause posterior ankle impingement.',
    originBones: ['fibula_r', 'fibula_l'], insertionBones: ['toe_dp_r1', 'toe_dp_l1'],
  },
  {
    id: 'popliteus', name: 'Popliteus', latinName: 'Musculus popliteus', category: 'leg',
    origin: 'Lateral femoral condyle (lateral surface) and arcuate ligament',
    insertion: 'Posterior surface of tibia (above soleal line)',
    function: '"Unlocks" the knee from full extension by medially rotating tibia (or laterally rotating femur); stabilizes posterior knee',
    innervation: 'Tibial nerve (L4–S1)',
    bloodSupply: 'Popliteal artery, posterior tibial recurrent artery',
    clinicalNotes: 'Key structure in posterior corner of knee. Popliteus tendinopathy causes lateral knee pain (differentiate from LCL injury). Popliteus tenosynovitis in downhill runners. "Key that unlocks the knee" — initiates flexion from full extension.',
    originBones: ['femur_r', 'femur_l'], insertionBones: ['tibia_r', 'tibia_l'],
  },
  // ─── FOOT MUSCLES ──────────────────────────────────────────────────────────
  {
    id: 'flexor_digitorum_brevis', name: 'Flexor Digitorum Brevis', latinName: 'Musculus flexor digitorum brevis', category: 'foot',
    origin: 'Medial tubercle of calcaneus; plantar fascia',
    insertion: 'Middle phalanges of toes 2–5 (splits to allow FDL to pass through)',
    function: 'Flexes toes 2–5 at proximal IP joint; supports longitudinal arch',
    innervation: 'Medial plantar nerve (L5–S1)',
    bloodSupply: 'Medial and lateral plantar arteries',
    clinicalNotes: 'First layer of plantar foot muscles. Plantar fasciitis: inflammation at FDB origin on calcaneus — heel pain on first steps in morning. Plantar fascia (above FDB) forms plantar aponeurosis.',
    originBones: ['calcaneus_r', 'calcaneus_l'], insertionBones: ['toe_mp_r1', 'toe_mp_r2', 'toe_mp_r3', 'toe_mp_r4'],
  },
  {
    id: 'abductor_hallucis', name: 'Abductor Hallucis', latinName: 'Musculus abductor hallucis', category: 'foot',
    origin: 'Medial tubercle of calcaneus; plantar fascia; flexor retinaculum',
    insertion: 'Medial side of proximal phalanx of hallux',
    function: 'Abducts and flexes great toe; supports medial longitudinal arch',
    innervation: 'Medial plantar nerve (L5–S1)',
    bloodSupply: 'Medial plantar artery',
    clinicalNotes: 'Forms medial border of foot sole. Compressed in tarsal tunnel syndrome. Visible bulk on medial foot. Important in hallux valgus (bunion) — becomes elongated and weakened as great toe deviates laterally.',
    originBones: ['calcaneus_r', 'calcaneus_l'], insertionBones: ['toe_pp_r1', 'toe_pp_l1'],
  },
  {
    id: 'extensor_digitorum_brevis', name: 'Extensor Digitorum Brevis', latinName: 'Musculus extensor digitorum brevis', category: 'foot',
    origin: 'Anterolateral surface of calcaneus',
    insertion: 'Bases of proximal phalanges of toes 1–4 (and EDL tendons 2–4)',
    function: 'Extends toes 1–4',
    innervation: 'Deep peroneal nerve (L5–S1)',
    bloodSupply: 'Dorsalis pedis artery',
    clinicalNotes: 'Only intrinsic muscle on dorsum of foot. Bulk visible on dorsolateral foot — swelling here suggests injury (fracture, sinus tarsi syndrome) or tumor. Deep peroneal nerve terminates between EDB and toes 1–2 — provides sensation in first web space.',
    originBones: ['calcaneus_r', 'calcaneus_l'], insertionBones: ['toe_pp_r1', 'toe_pp_r2', 'toe_pp_r3', 'toe_pp_r4'],
  },
  {
    id: 'abductor_digiti_minimi_foot', name: 'Abductor Digiti Minimi (Foot)', latinName: 'Musculus abductor digiti minimi pedis', category: 'foot',
    origin: 'Lateral and medial tubercles of calcaneus; plantar fascia',
    insertion: 'Lateral side of proximal phalanx of little toe',
    function: 'Abducts and flexes little toe; supports lateral arch',
    innervation: 'Lateral plantar nerve (S1–S2)',
    bloodSupply: 'Lateral plantar artery',
    clinicalNotes: 'Forms lateral border of foot sole. Common site for plantar fibromatosis. Lateral heel pain from Baxter\'s nerve (first branch of lateral plantar nerve) entrapment — differential for plantar fasciitis.',
    originBones: ['calcaneus_r', 'calcaneus_l'], insertionBones: ['toe_pp_r5', 'toe_pp_l5'],
  },
  {
    id: 'flexor_hallucis_brevis', name: 'Flexor Hallucis Brevis', latinName: 'Musculus flexor hallucis brevis', category: 'foot',
    origin: 'Plantar surfaces of cuboid and lateral cuneiform; tendon of tibialis posterior',
    insertion: 'Medial and lateral sides of base of proximal phalanx of hallux (with sesamoids)',
    function: 'Flexes great toe at MTP joint; bears weight on medial forefoot',
    innervation: 'Medial plantar nerve (L5–S1)',
    bloodSupply: 'Medial plantar artery, first plantar metatarsal artery',
    clinicalNotes: 'Contains two sesamoid bones (medial and lateral) at hallux MTP joint — protect FHL tendon. Sesamoiditis: pain beneath ball of foot. Sesamoid fractures in dancers and runners.',
    originBones: ['cuboid_r', 'cuboid_l', 'cuneiform1_r', 'cuneiform1_l'], insertionBones: ['toe_pp_r1', 'toe_pp_l1'],
  },
];

export const MUSCLE_CATEGORIES = [
  { key: 'head',       label: 'Head',       count: 8  },
  { key: 'neck',       label: 'Neck',       count: 5  },
  { key: 'back',       label: 'Back',       count: 7  },
  { key: 'chest',      label: 'Chest',      count: 5  },
  { key: 'shoulder',   label: 'Shoulder',   count: 6  },
  { key: 'arm',        label: 'Arm',        count: 4  },
  { key: 'forearm',    label: 'Forearm',    count: 7  },
  { key: 'hand',       label: 'Hand',       count: 4  },
  { key: 'abdominal',  label: 'Abdominal',  count: 5  },
  { key: 'hip',        label: 'Hip',        count: 6  },
  { key: 'thigh',      label: 'Thigh',      count: 8  },
  { key: 'leg',        label: 'Leg',        count: 8  },
  { key: 'foot',       label: 'Foot',       count: 5  },
];
