// nerve_data.js — Real mesh name → data mapping for human-nervous-system.glb
// Model source: Human Atlas / BodyParts3D (CC BY-SA 2.1 Japan)
// Mesh names follow pattern: "Structure name.j.001" / ".r.001" / ".l.001"
// The loader strips suffixes and does case-insensitive fuzzy matching.

export const NERVE_CATEGORIES = [
  { id: 'brain',            label: 'ncat_brain' },
  { id: 'spinal_cord',     label: 'ncat_spinal_cord' },
  { id: 'cranial_nerves',  label: 'ncat_cranial_nerves' },
  { id: 'peripheral',      label: 'ncat_peripheral_nerves' },
];

// meshKeywords: array of strings that, if found in a mesh name (lowercased, suffix-stripped),
// will map that mesh to this nerve entry.
export const NERVE_DB = [
  // ─── Brain ────────────────────────────────────────────────────────────────
  {
    id: 'nerve_brain',
    name: 'n_brain',
    latinName: 'Encephalon',
    category: 'brain',
    meshKeywords: ['brain.j', 'cerebrum.j', 'encephalon'],
    description: 'desc_brain',
    function: 'func_brain',
    clinicalNotes: 'clin_brain',
    relatedStructures: ['nerve_cerebellum', 'nerve_brainstem'],
  },
  {
    id: 'nerve_cerebellum',
    name: 'n_cerebellum',
    latinName: 'Cerebellum',
    category: 'brain',
    meshKeywords: ['cerebellum.j', 'tonsil of cerebellum', 'cerebellar peduncle'],
    description: 'desc_cerebellum',
    function: 'func_cerebellum',
    clinicalNotes: 'clin_cerebellum',
    relatedStructures: ['nerve_brain', 'nerve_brainstem'],
  },
  {
    id: 'nerve_brainstem',
    name: 'n_brainstem',
    latinName: 'Truncus encephali',
    category: 'brain',
    meshKeywords: ['brainstem.j', 'midbrain.j', 'pons.j', 'medulla oblongata'],
    description: 'desc_brainstem',
    function: 'func_brainstem',
    clinicalNotes: 'clin_brainstem',
    relatedStructures: ['nerve_brain', 'nerve_spinal_cord'],
  },
  {
    id: 'nerve_cerebral_hemisphere',
    name: 'n_cerebral_hemisphere',
    latinName: 'Hemispherium cerebri',
    category: 'brain',
    meshKeywords: ['cerebral hemisphere'],
    description: 'desc_cerebral_hemisphere',
    function: 'func_cerebral_hemisphere',
    clinicalNotes: 'clin_cerebral_hemisphere',
    relatedStructures: ['nerve_brain'],
  },
  {
    id: 'nerve_basal_forebrain',
    name: 'n_basal_forebrain',
    latinName: 'Prosencephalon basale',
    category: 'brain',
    meshKeywords: ['basal forebrain'],
    description: 'desc_basal_forebrain',
    function: 'func_basal_forebrain',
    clinicalNotes: 'clin_basal_forebrain',
    relatedStructures: ['nerve_brain'],
  },

  // ─── Spinal Cord ──────────────────────────────────────────────────────────
  {
    id: 'nerve_spinal_cord',
    name: 'n_spinal_cord',
    latinName: 'Medulla spinalis',
    category: 'spinal_cord',
    meshKeywords: ['spinal cord.j', 'grey matter of spinal cord', 'white matter of spinal cord'],
    description: 'desc_spinal_cord',
    function: 'func_spinal_cord',
    clinicalNotes: 'clin_spinal_cord',
    relatedStructures: ['nerve_brainstem', 'nerve_spinal_nerves'],
  },
  {
    id: 'nerve_spinal_dura',
    name: 'n_spinal_dura',
    latinName: 'Dura mater spinalis',
    category: 'spinal_cord',
    meshKeywords: ['spinal dura'],
    description: 'desc_spinal_dura',
    function: 'func_spinal_dura',
    clinicalNotes: 'clin_spinal_dura',
    relatedStructures: ['nerve_spinal_cord'],
  },
  {
    id: 'nerve_spinal_nerves',
    name: 'n_spinal_nerves',
    latinName: 'Nervi spinales',
    category: 'spinal_cord',
    meshKeywords: ['spinal nerves.j'],
    description: 'desc_spinal_nerves',
    function: 'func_spinal_nerves',
    clinicalNotes: 'clin_spinal_nerves',
    relatedStructures: ['nerve_spinal_cord'],
  },

  // ─── Cranial Nerves ───────────────────────────────────────────────────────
  {
    id: 'nerve_olfactory',
    name: 'n_olfactory',
    latinName: 'Nervus olfactorius (I)',
    category: 'cranial_nerves',
    meshKeywords: ['olfactory nerve'],
    description: 'desc_olfactory',
    function: 'func_olfactory',
    clinicalNotes: 'clin_olfactory',
    relatedStructures: ['nerve_brain'],
  },
  {
    id: 'nerve_optic',
    name: 'n_optic',
    latinName: 'Nervus opticus (II)',
    category: 'cranial_nerves',
    meshKeywords: ['optic nerve'],
    description: 'desc_optic',
    function: 'func_optic',
    clinicalNotes: 'clin_optic',
    relatedStructures: ['nerve_brain'],
  },
  {
    id: 'nerve_oculomotor',
    name: 'n_oculomotor',
    latinName: 'Nervus oculomotorius (III)',
    category: 'cranial_nerves',
    meshKeywords: ['oculomotor nerve'],
    description: 'desc_oculomotor',
    function: 'func_oculomotor',
    clinicalNotes: 'clin_oculomotor',
    relatedStructures: ['nerve_brain'],
  },
  {
    id: 'nerve_trigeminal',
    name: 'n_trigeminal',
    latinName: 'Nervus trigeminus (V)',
    category: 'cranial_nerves',
    meshKeywords: ['trigeminal nerve', 'mandibular nerve', 'sensory root of trigeminal'],
    description: 'desc_trigeminal',
    function: 'func_trigeminal',
    clinicalNotes: 'clin_trigeminal',
    relatedStructures: ['nerve_brain'],
  },
  {
    id: 'nerve_facial',
    name: 'n_facial',
    latinName: 'Nervus facialis (VII)',
    category: 'cranial_nerves',
    meshKeywords: ['facial nerve', 'motor nucleus of facial'],
    description: 'desc_facial',
    function: 'func_facial',
    clinicalNotes: 'clin_facial',
    relatedStructures: ['nerve_brain'],
  },
  {
    id: 'nerve_vagus',
    name: 'n_vagus',
    latinName: 'Nervus vagus (X)',
    category: 'cranial_nerves',
    meshKeywords: ['vagus nerve', 'vagal'],
    description: 'desc_vagus',
    function: 'func_vagus',
    clinicalNotes: 'clin_vagus',
    relatedStructures: ['nerve_brainstem'],
  },

  // ─── Peripheral Nerves ────────────────────────────────────────────────────
  {
    id: 'nerve_sciatic',
    name: 'n_sciatic',
    latinName: 'Nervus ischiadicus',
    category: 'peripheral',
    meshKeywords: ['sciatic nerve', 'ischiadicus'],
    description: 'desc_sciatic',
    function: 'func_sciatic',
    clinicalNotes: 'clin_sciatic',
    relatedStructures: ['nerve_spinal_cord'],
  },
  {
    id: 'nerve_cranial_group',
    name: 'n_cranial_nerves_group',
    latinName: 'Nervi craniales',
    category: 'cranial_nerves',
    meshKeywords: ['cranial nerves.j'],
    description: 'desc_cranial_nerves_group',
    function: 'func_cranial_nerves_group',
    clinicalNotes: 'clin_cranial_nerves_group',
    relatedStructures: ['nerve_brain'],
  },
];
