
export const state = {
  currentMode: 'normal',
  selectedBone: null,
  hoveredBone: null,
  isExploded: false,
  isRotating: false,
  labelsOn: false,
  currentFilter: 'all',
  boneMeshes: {},
  boneBasePositions: {},
  boneBaseScales: {},
  boneBaseQuaternions: {},
  labels: {},
  modelGroup: null,
  boneAllMeshes: [],
  boneMeshGroups: {},
  isMeasuring: false,
  isAnnotating: false,
  isXRay: false,
  isSection: false,
  isPresentationMode: false,
  isIsolated: false,
  annotations: {},
  annotationMeshes: {},
  annotationLabels: {},
};
